// index/js/savollar.js
const ZiyomapBaza = {
  
 // ========================================================
  // 1. QUIZ MUSOBAQA SAVOLLARI (Fanlar va Darajalar bo'yicha)
  // ========================================================
  quiz: {
    fizika: {
      oson: [
        { question: "Tezlik qaysi harf bilan belgilanadi?", options: ["v", "m", "F", "t"], answer: "v" },
        { question: "Xalqaro birliklar sistemasida (SI) vaqt birligi nima?", options: ["soat", "minut", "sekund", "sutka"], answer: "sekund" },
        { question: "Kuchni o'lchaydigan asbob qanday nomlanadi?", options: ["Termometr", "Dinamometr", "Barometr", "Voltmetr"], answer: "Dinamometr" },
        { question: "Modda nechta asosiy agregat holatda bo'lishi mumkin?", options: ["2 ta", "3 ta", "4 ta", "5 ta"], answer: "4 ta" },
        { question: "Ovoz havodan ko'ra qaysi muhitda tezroq tarqaladi?", options: ["Vakuumda", "Suvda (qattiq jismlarda)", "Gazda", "Hech qayerda"], answer: "Suvda (qattiq jismlarda)" },
        { question: "Tabiatda eng tez harakatlanadigan narsa nima?", options: ["Ovoz", "Yorug'lik", "Samolyot", "Yer sharining aylanishi"], answer: "Yorug'lik" },
        { question: "Massa qaysi asbob yordamida o'lchanadi?", options: ["Tarozida", "Lineykada", "Dinamometrda", "Menzurkada"], answer: "Tarozida" },
        { question: "Kuchsizlanish yoki ishqalanish kuchi harakatga nisbatan qanday yo'naladi?", options: ["Harakat yo'nalishida", "Harakatga qarshi", "Tik yuqoriga", "Yo'nalishga ega emas"], answer: "Harakatga qarshi" },
        { question: "Suv necha gradus selsiyda qaynaydi?", options: ["50 °C", "80 °C", "100 °C", "0 °C"], answer: "100 °C" },
        { question: "Erkin tushish tezlanishi g ning qiymati taxminan nechaga teng?", options: ["5 m/s²", "9.8 m/s²", "15 m/s²", "0 m/s²"], answer: "9.8 m/s²" }
      ],
      orta: [
        { question: "Nyutonning ikkinchi qonuni formulasini ko'rsating.", options: ["F = m*a", "E = m*c²", "P = m*v", "v = s/t"], answer: "F = m*a" },
        { question: "Bosim qaysi birlikda o'lchanadi?", options: ["Joul", "Vatt", "Paskal", "Nyuton"], answer: "Paskal" },
        { question: "Kinetik energiya qaysi formula bilan hisoblanadi?", options: ["m*g*h", "F*s", "(m*v²)/2", "I*R"], answer: "(m*v²)/2" },
        { question: "Guk qonuniga ko'ra elastiklik kuchi qanday ifodalanadi?", options: ["F = -k*x", "F = m*g", "F = G*(m1*m2)/r²", "F = q*E"], answer: "F = -k*x" },
        { question: "Ideal gaz holat tenglamasi (Mendeleyev-Klapeyron) qaysi?", options: ["PV = nRT", "P = F/S", "V = m/p", "Q = cmT"], answer: "PV = nRT" },
        { question: "O'tkazgich qarshiligi nimalarga bog'liq?", options: ["Faqat kuchlanishga", "Uzunligi, ko'ndalang kesim yuzi va modda turiga", "Faqat tok kuchiga", "Hech narsaga bog'liq emas"], answer: "Uzunligi, ko'ndalang kesim yuzi va modda turiga" },
        { question: "Matematik mayatnik tebranish davri qaysi kattalikka bog'liq emas?", options: ["Mayatnik uzunligiga", "Massa", "Erkin tushish tezlanishiga", "Piga"], answer: "Massa" },
        { question: "Yorug'likning qaytish qonuniga ko'ra, tushish burchagi alfa nimaga teng?", options: ["Qaytish burchagi betaga", "90 gradusga", "Sinf burchagi gammaga", "0 ga"], answer: "Qaytish burchagi betaga" },
        { question: "Transformatorning vazifasi nima?", options: ["O'zgarmas tokni o'zgaruvchan qilish", "Kuchlanishni o'zgartirish", "Mexanik energiyani elektrga aylantirish", "Qarshilikni yo'qotish"], answer: "Kuchlanishni o'zgartirish" },
        { question: "Absolyut nol harorat necha gradus Selsiyga teng?", options: ["0 °C", "-100 °C", "-273.15 °C", "-450 °C"], answer: "-273.15 °C" }
      ],
      qiyin: [
        { question: "Kvant fizikasi asoschisi bo'lgan olim kim?", options: ["Albert Eynshteyn", "Maks Plank", "Nil Bor", "Ervin Shredinger"], answer: "Maks Plank" },
        { question: "Yorug'likning shaffof muhitlar chegarasidan o'tishida to'liq ichki qaytish hosil bo'lish sharti nima?", options: ["Nur optik zichligi kichik muhitdan katta muhitga o'tishi kerak", "Nur optik zichligi katta muhitdan kichik muhitga chegaraviy burchakdan katta burchak ostida tushishi kerak", "Tushish burchagi 0 ga teng bo'lishi kerak", "Muhitlar zichligi teng bo'lishi kerak"], answer: "Nur optik zichligi katta muhitdan kichik muhitga chegaraviy burchakdan katta burchak ostida tushishi kerak" },
        { question: "Karnoning issiqlik mashinasi FIK (Foydali ish koeffitsiyenti) qaysi formula bilan aniqlanadi?", options: ["(T1 - T2) / T1", "(T1 + T2) / T2", "T2 / T1", "1 - T1/T2"], answer: "(T1 - T2) / T1" },
        { question: "Geyger-Marsden tajribasida alfa zarralar oltin folgadan sochilganda atomning qaysi tuzilishi isbotlandi?", options: ["Elektron qobig'i", "Neytron mavjudligi", "Atom yadrosining mavjudligi", "Kvant sathlari"], answer: "Atom yadrosining mavjudligi" },
        { question: "Lorents kuchi formulasini ko'rsating.", options: ["F = q*v*B*sin(a)", "F = I*L*B*sin(a)", "F = m*g", "F = k*q1*q2/r²"], answer: "F = q*v*B*sin(a)" },
        { question: "Foton energiyasi ifodasi qaysi?", options: ["E = h*v", "E = m*g", "E = p*v", "E = k*x"], answer: "E = h*v" },
        { question: "Eynshteynning fotoeffekt uchun tenglamasini aniqlang.", options: ["hv = A_chiq + E_kin", "E = mc²", "F = dp/dt", "lambda = h/p"], answer: "hv = A_chiq + E_kin" },
        { question: "Induktivlik g'altagidagi magnit maydon energiyasi qanday hisoblanadi?", options: ["(L*I²)/2", "(C*U²)/2", "I²*R*t", "q*U"], answer: "(L*I²)/2" },
        { question: "Eynshteynning maxsus nisbiylik nazariyasiga ko'ra qaysi kattalik barcha inersial sanoq sistemalarida o'zgarmasdir?", options: ["Vaqt", "Massa", "Vakuumdagi yorug'lik tezligi", "Jism uzunligi"], answer: "Vakuumdagi yorug'lik tezligi" },
        { question: "Doppler effekti nimani anglatadi?", options: ["Yorug'likning sinishini", "Kuzatuvchiga nisbatan manba harakat qilganda to'lqin chastotasining o'zgarishini", "Jismning qizib nurlanishini", "Zarraning to'lqin xususiyatini"], answer: "Kuzatuvchiga nisbatan manba harakat qilganda to'lqin chastotasining o'zgarishini" }
      ]
    },
    matematika: {
      oson: [
        { question: "Qaysi son barcha sonlarga bo'linadi yoki har qanday songa ko'paytirilsa nol bo'ladi?", options: ["1", "0", "10", "Chistlo"], answer: "0" },
        { question: "Kvadratning perimetri formulasi qaysi?", options: ["P = 4a", "P = a²", "P = 2(a+b)", "P = a*b"], answer: "P = 4a" },
        { question: "Eng kichik tub sonni toping.", options: ["1", "2", "3", "0"], answer: "2" },
        { question: "Uchburchakning ichki burchaklari yig'indisi necha gradus?", options: ["90°", "180°", "360°", "270°"], answer: "180°" },
        { question: "25 sonining kvadrat ildizi nechaga teng?", options: ["3", "4", "5", "6"], answer: "5" },
        { question: "Tenglamani yeching: 2x + 5 = 15", options: ["x = 5", "x = 10", "x = 7", "x = 4"], answer: "x = 5" },
        { question: "Doiraning yuzi formulasi qaysi?", options: ["S = pi*r²", "S = 2*pi*r", "S = a*b", "S = d²"], answer: "S = pi*r²" },
        { question: "O'tdi o'tkir burchak necha gradusdan kichik bo'ladi?", options: ["45°", "90°", "180°", "60°"], answer: "90°" },
        { question: "120 ning 20 foizi nechaga teng?", options: ["20", "24", "12", "30"], answer: "24" },
        { question: "To'g'ri to'rtburchakning bo'yi 6 sm, eni 4 sm. Uning yuzini toping.", options: ["10 sm²", "24 sm²", "20 sm²", "12 sm²"], answer: "24 sm²" }
      ],
      orta: [
        { question: "Kvadrat tenglamaning diskriminant formulasi qaysi?", options: ["D = b² - 4ac", "D = b² + 4ac", "D = a² - 4bc", "D = -b ± sqrt(D)"], answer: "D = b² - 4ac" },
        { question: "log_2(8) ifodaning qiymati nechaga teng?", options: ["2", "3", "4", "1"], answer: "3" },
        { question: "Arifmetik progressiyada a1 = 3, d = 4 bo'lsa, 5-hadni toping.", options: ["15", "19", "23", "11"], answer: "19" },
        { question: "sin²(x) + cos²(x) nimaga teng?", options: ["0", "1", "tan(x)", "2"], answer: "1" },
        { question: "Kombinatorikada 4! (to'rt faktorial) qiymati nechaga teng?", options: ["12", "24", "16", "4"], answer: "24" },
        { question: "f(x) = x³ funksiyaning hosilasini toping.", options: ["3x²", "x²", "3x", "2x³"], answer: "3x²" },
        { question: "Agar kubning qirrasi 3 sm bo'lsa, uning hajmi necha sm³ bo'ladi?", options: ["9", "18", "27", "12"], answer: "27" },
        { question: "Viyet teoremasiga ko'ra x² - 7x + 12 = 0 tenglama ildizlari ko'paytmasi nechaga teng?", options: ["7", "-7", "12", "-12"], answer: "12" },
        { question: "Geometrik progressiyada b1 = 2, q = 3 bo'lsa, dastlabki 3 ta had yig'indisini toping.", options: ["12", "26", "18", "20"], answer: "26" },
        { question: "Ikki to'g'ri chiziq kesishgandagi vertikal burchaklar haqida qaysi tasdiq to'g'ri?", options: ["Yig'indisi 180°", "Ular o'zaro teng", "Yig'indisi 90°", "Ular doim o'tkir burchakdir"], answer: "Ular o'zaro teng" }
      ],
      qiyin: [
        { question: "f(x) = sin(x) funksiyaning boshlang'ich funksiyasini (integralini) toping.", options: ["cos(x) + C", "-cos(x) + C", "sin(x) + C", "-sin(x) + C"], answer: "-cos(x) + C" },
        { question: "lim (x->0) (sin(x) / x) ajoyib limit qiymati nimaga teng?", options: ["0", "1", "Cheksizlik", "Mavjud emas"], answer: "1" },
        { question: "Kompleks son i² nimaga teng?", options: ["1", "-1", "0", "sqrt(-1)"], answer: "-1" },
        { question: "Skalyar ko'paytmasi 0 ga teng bo'lgan ikki vektor qanday joylashgan?", options: ["Paralell", "Perpendikulyar", "Ustma-ust", "Kesishmaydi"], answer: "Perpendikulyar" },
        { question: "Tenglamani yeching: 3^(x+2) + 3^x = 90", options: ["x = 2", "x = 3", "x = 1", "x = 4"], answer: "x = 2" },
        { question: "Skalyar kattalik emas, balki vektor kattalikni ko'rsating.", options: ["Tezlik (Matematik/Fizik kontekstda yo'nalishli kesma)", "Yuz", "Hajm", "Massa"], answer: "Tezlik (Matematik/Fizik kontekstda yo'nalishli kesma)" },
        { question: "f(x) = ln(x) funksiyaning hosilasi nimaga teng?", options: ["1/x", "e^x", "1/(x²)", "ln(x)/x"], answer: "1/x" },
        { question: "Sferaning to'liq sirt yuzi formulasi qaysi?", options: ["4*pi*r²", "2*pi*r²", "(4/3)*pi*r³", "pi*r²*h"], answer: "4*pi*r²" },
        { question: "Determinantni hisoblang: [[2, 3], [1, 5]]", options: ["13", "7", "10", "5"], answer: "7" },
        { question: "Nyuton-Leybnits formulasi nima uchun xizmat qiladi?", options: ["Hosilani hisoblash uchun", "Aniq integralni hisoblash uchun", "Kvadrat tenglamani yechish uchun", "Progressiyani topish uchun"], answer: "Aniq integralni hisoblash uchun" }
      ]
    },
    informatika: {
      oson: [
        { question: "Kompyuterning eng asosiy miyasi hisoblangan qurilma qaysi?", options: ["Monitor", "Processor (Markaziy protsessor)", "Klaviatura", "Sichqoncha"], answer: "Processor (Markaziy protsessor)" },
        { question: "1 Bayt necha bitga teng?", options: ["4 bit", "8 bit", "1024 bit", "16 bit"], answer: "8 bit" },
        { question: "Axborotning eng kichik o'lchov birligi nima?", options: ["Bayt", "Kilobayt", "Bit", "Megabayt"], answer: "Bit" },
        { question: "Matn muharririni ko'rsating.", options: ["Microsoft Word", "Microsoft Excel", "Microsoft Paint", "Google Chrome"], answer: "Microsoft Word" },
        { question: "Kompyuterni zararli dasturlardan himoya qiluvchi dastur qanday ataladi?", options: ["Brauzer", "Antivirus", "Drayver", "Utilit"], answer: "Antivirus" },
        { question: "Faylni butunlay (savatga tashlamasdan) o'chirish uchun qaysi tugmalar bosiladi?", options: ["Ctrl + Delete", "Shift + Delete", "Alt + Delete", "Backspace"], answer: "Shift + Delete" },
        { question: "Internet sahifalarini ko'rish uchun mo'ljallangan dasturlar nima deyiladi?", options: ["Pleyer", "Brauzer", "Prezentatsiya", "Arxivator"], answer: "Brauzer" },
        { question: "Nusxa olish (Kopirovat) tezkor tugmalari qaysi?", options: ["Ctrl + V", "Ctrl + X", "Ctrl + C", "Ctrl + Z"], answer: "Ctrl + C" },
        { question: "Loyiha prezentatsiyalarini (taqdimot) tayyorlash dasturi qaysi?", options: ["MS Excel", "MS PowerPoint", "MS Access", "MS Word"], answer: "MS PowerPoint" },
        { question: "Kompyuter yoqilganda birinchi bo'lib yuklanadigan tizim dasturi qaysi?", options: ["Operatsion tizim (OS)", "Telegram", "Photoshop", "Ofis dasturlari"], answer: "Operatsion tizim (OS)" }
      ],
      orta: [
        { question: "HTML nima?", options: ["Dasturlash tili", "Gipermatnli belgilash tili (Sahifa karkasi)", "Ma'lumotlar bazasi", "Grafik muharrir"], answer: "Gipermatnli belgilash tili (Sahifa karkasi)" },
        { question: "Python dasturlash tilida konsolga ma'lumot chiqarish buyrug'i qaysi?", options: ["input()", "print()", "echo()", "Console.WriteLine()"], answer: "print()" },
        { question: "1 Kilobayt necha baytga teng?", options: ["1000", "1024", "512", "2048"], answer: "1024" },
        { question: "IP manzil (IPv4) nechta qismdan iborat bo'ladi?", options: ["2 ta", "3 ta", "4 ta", "6 ta"], answer: "4 ta" },
        { question: "SQL nima maqsadda ishlatiladi?", options: ["Saytlarni bezash uchun", "Ma'lumotlar bazasi bilan ishlash uchun", "Dasturni kompilyatsiya qilish uchun", "Rasm chizish uchun"], answer: "Ma'lumotlar bazasi bilan ishlash uchun" },
        { question: "CSS ning asosiy vazifasi nimadan iborat?", options: ["Mantiqiy hisob-kitob qilish", "Veb-sahifaga vizual uslub va dizayn berish", "Server bilan bog'lanish", "Fayllarni arxivlash"], answer: "Veb-sahifaga vizual uslub va dizayn berish" },
        { question: "Python dasturlash tilida ro'yxat (list) qaysi qavs ichida e'lon qilinadi?", options: ["( )", "{ }", "[ ]", "< >"], answer: "[ ]" },
        { question: "Kompyuter tarmoqlarini uzoq masofaga xatosiz va juda tez uzatuvchi kabel turi qaysi?", options: ["Koaksial", "Eshilgan juftlik (UTP)", "Optik tolali kabel (Optovoloqno)", "Telefon kabeli"], answer: "Optik tolali kabel (Optovoloqno)" },
        { question: "Dasturlashda o'zgaruvchi turini ifodalovchi 'float' nimani anglatadi?", options: ["Butun son", "Matn", "Haqiqiy (haqiqiy/o'nlik) son", "Mantiqiy tur"], answer: "Haqiqiy (haqiqiy/o'nlik) son" },
        { question: "URL nima?", options: ["Veb-sahifaning internetdagi aniq manzili", "Kompyuterning protsessor turi", "Fayl formati", "Dasturlash muhiti"], answer: "Veb-sahifaning internetdagi aniq manzili" }
      ],
      qiyin: [
        { question: "Obyektga yo'naltirilgan dasturlashning (OOP) 3 ta asosiy ustuni qaysilar?", options: ["Sikl, Shart, O'zgaruvchi", "Inkapsulyatsiya, Vorislik, Polimorfizm", "Kompilyatsiya, Interpretatsiya, Linker", "Massiv, Stek, Navbat"], answer: "Inkapsulyatsiya, Vorislik, Polimorfizm" },
        { question: "Algoritmning murakkabligini baholashda ishlatiladigan 'Big O' nimani bildiradi?", options: ["Xotira hajmini aniq baytda ko'rsatadi", "Algoritm bajarilish vaqtining kiruvchi ma'lumotga bog'liqlik o'sish darajasini", "Dasturdagi xatolar sonini", "Ma'lumotlar bazasi aloqalarini"], answer: "Algoritm bajarilish vaqtining kiruvchi ma'lumotga bog'liqlik o'sish darajasini" },
        { question: "O'n oltilik (Hexadecimal) sanoq sistemasidagi 'F' harfi o'nlik tizimda qaysi songa to'g'ri keladi?", options: ["10", "15", "16", "11"], answer: "15" },
        { question: "Shifrlashda simmetrik va asimmetrik usullarning asosiy farqi nimada?", options: ["Simmetrikda kalit ishlatilmaydi", "Simmetrik shifrlashda shifrlash va deshifrlash uchun bitta kalitdan, asimmetrikda esa ochiq va yopiq kalitlar juftligidan foydalaniladi", "Asimmetrik shifrlash juda tez ishlaydi", "Hech qanday farqi yo'q"], answer: "Simmetrik shifrlashda shifrlash va deshifrlash uchun bitta kalitdan, asimmetrikda esa ochiq va yopiq kalitlar juftligidan foydalaniladi" },
        { question: "OSI modelining eng yuqori (7-bosqichi) qanday nomlanadi?", options: ["Transport bosqichi", "Tarmoq bosqichi", "Ilova (Amaliy) bosqichi - Application", "Fizik bosqich"], answer: "Ilova (Amaliy) bosqichi - Application" },
        { question: "Ma'lumotlar tuzilmasida LIFO (Last In, First Out) tamoyili asosida ishlaydigan tuzilma qaysi?", options: ["Navbat (Queue)", "Stek (Stack)", "Graf (Graph)", "Daraxt (Tree)"], answer: "Stek (Stack)" },
        { question: "Dasturni mashina kodiga to'liq tarjima qilib, keyin ishga tushiradigan instrumental dastur nima deyiladi?", options: ["Interpretator", "Kompilyator", "Drayver", "Baza"], answer: "Kompilyator" },
        { question: "Relyatsion ma'lumotlar bazasida ikki jadvalni bog'lash uchun ishlatiladigan kalit nima deyiladi?", options: ["Primary Key", "Foreign Key", "Unique Key", "Super Key"], answer: "Foreign Key" },
        { question: "Git tizimida masofaviy repozitoriyadagi o'zgarishlarni yuklab olish va joriy tarmoqqa birlashtirish buyrug'i qaysi?", options: ["git push", "git commit", "git pull", "git status"], answer: "git pull" },
        { question: "Rekursiya nima?", options: ["Sikl operatorining boshqa nomi", "Funksiyaning o'z-o'ziga to'g'ridan-to'g'ri yoki bilvosita murojaat qilishi", "Massiv elementlarini saralash", "Xatolarni ushlash mexanizmi"], answer: "Funksiyaning o'z-o'ziga to'g'ridan-to'g'ri yoki bilvosita murojaat qilishi" }
      ]
    },
    biologiya: {
      oson: [
        { question: "Tirik organizmlarning eng kichik tuzilish va funksional birligi nima?", options: ["To'qima", "Hujayra", "A'zo", "Molekula"], answer: "Hujayra" },
        { question: "O'simliklar quyosh nuri yordamida organik modda ishlab chiqarish jarayoni nima deyiladi?", options: ["Fotosintez", "Nafas olish", "Transpiratsiya", "Guttatsiya"], answer: "Fotosintez" },
        { question: "Inson tanasidagi eng asosiy qon aylanish markazi bo'lgan a'zo qaysi?", options: ["O'pka", "Jigar", "Yurak", "Buyrak"], answer: "Yurak" },
        { question: "Biologiya fani nimani o'rganadi?", options: ["Tirik tabiatni", "Toshlarni", "Kimyoviy elementlarni", "Yulduzlarni"], answer: "Tirik tabiatni" },
        { question: "O'simliklarni o'rganadigan biologiya bo'limi qanday ataladi?", options: ["Zoologiya", "Botanika", "Mikologiya", "Anatomiya"], answer: "Botanika" },
        { question: "Inson o'pkasi orqali havoga qaysi gazni chiqaradi?", options: ["Kislorod", "Azot", "Karbonat angidrid", "Vodorod"], answer: "Karbonat angidrid" },
        { question: "Baliqlar qaysi a'zosi yordamida nafas oladi?", options: ["O'pka", "Jabra", "Teri", "Traxeya"], answer: "Jabra" },
        { question: "Qizil qon hujayralari (eritrotsitlar) tarkibidagi temir tutgan oqsil qanday nomlanadi?", options: ["Insulin", "Gemoglobin", "Xitin", "Keratin"], answer: "Gemoglobin" },
        { question: "O'simlikka yashil rang beruvchi pigment nima?", options: ["Xlorofill", "Karotin", "Xantofill", "Melanin"], answer: "Xlorofill" },
        { question: "Qo'ziqorinlarni o'rganadigan fan nima?", options: ["Botanika", "Mikologiya", "Zoologiya", "Bakteriologiya"], answer: "Mikologiya" }
      ],
      orta: [
        { question: "Genetika fanining otasi deb kim tan olingan?", options: ["Charlz Darvin", "Gregor Mendel", "Lui Paster", "Robert Guk"], answer: "Gregor Mendel" },
        { question: "Hujayraning 'energiya stansiyasi' deb ataluvchi organoid qaysi?", options: ["Ribosoma", "Mitoxondriya", "Lizosoma", "Golji majmuasi"], answer: "Mitoxondriya" },
        { question: "Inson tanasida nechta xromosoma bor?", options: ["23 ta", "46 ta", "48 ta", "32 ta"], answer: "46 ta" },
        { options: ["A", "B", "C", "D"], question: "Qaysi vitamin etishmasligi natijasida odamda skorburt (singa) kasalligi kelib chiqadi?", answer: "C" },
        { question: "O'simliklarda suv va unda erigan mineral moddalarni ildizdan yuqoriga o'tkazuvchi to'qima qaysi?", options: ["Floema", "Ksilema", "Kollorxirma", "Epidermis"], answer: "Ksilema" },
        { question: "Hujayrada oqsil sintezini qaysi organoid amalga oshiradi?", options: ["Ribosoma", "Vakuola", "Xloroplast", "Yadro"], answer: "Ribosoma" },
        { question: "Qon guruhlari nechta turga bo'linadi?", options: ["2 ta", "3 ta", "4 ta", "5 ta"], answer: "4 ta" },
        { question: "Insulin gormoni qaysi a'zo tomonidan ishlab chiqariladi?", options: ["Jigar", "Me'da osti bezi", "Buyrak usti bezi", "Qalqonsimon bez"], answer: "Me'da osti bezi" },
        { question: "Bakteriyalarni ko'payish usuli asosan qanday?", options: ["Murtak orqali", "Oddiy ikkiga bo'linish", "Jinsiy yo'l bilan", "Sport hosil qilib"], answer: "Oddiy ikkiga bo'linish" },
        { question: "Organizmlarning tashqi muhit o'zgarishlariga qaramay ichki muhit barqarorligini saqlash xususiyati nima deyiladi?", options: ["Evolutsiya", "Gomeostaz", "Mutatsiya", "Adaptatsiya"], answer: "Gomeostaz" }
      ],
      qiyin: [
        { question: "DNK replikatsiyasi (ikkilanishi) hujayra siklining qaysi davrida sodir bo'ladi?", options: ["Mitotik profaza", "Interfazaning sintetik (S) davrida", "Metafaza", "Telofaza"], answer: "Interfazaning sintetik (S) davrida" },
        { question: "Xromosomalarning hujayra ekvatori bo'ylab tekis tizilishi mitotik bo'linishning qaysi bosqichiga xos?", options: ["Profaza", "Anafaza", "Metafaza", "Telofaza"], answer: "Metafaza" },
        { question: "Kreb sikli (trikarbon kislotalar sikli) hujayraning qayerida kechadi?", options: ["Sitoplazmada", "Mitoxondriya matritsasida", "Ribosomada", "Yadroda"], answer: "Mitoxondriya matritsasida" },
        { question: "DNK zanjiridagi Adeninga (A) RNK sintezida qaysi nukleotid komplementar bo'ladi?", options: ["Timin (T)", "Urasil (U)", "Sitozin (C)", "Guanin (G)"], answer: "Urasil (U)" },
        { question: "Yurakning qaysi qismidan katta qon aylanish doirasi boshlanadi?", options: ["O'ng qorinchadan", "Chap qorinchadan", "O'ng bo'lmachadan", "Chap bo'lmachadan"], answer: "Chap qorinchadan" },
        { question: "O'simliklarda fototizim-II dagi suv fotolizi natijasida qaysi yon mahsulot ajralib chiqadi?", options: ["Glyukoza", "Kislorod gazi (O2)", "Karbonat angidrid", "ATF"], answer: "Kislorod gazi (O2)" },
        { question: "Tiriklikning evolutsion nazariyasini mukammal ishlab chiqqan va tabiiy tanlanishni asoslagan olim kim?", options: ["Jan Batist Lamark", "Charlz Darvin", "Gregor Mendel", "Karl Linney"], answer: "Charlz Darvin" },
        { question: "Gidra yoki achitqi zamburug'ining jinsiz ko'payish shakli qanday ataladi?", options: ["Kurtaklanish", "Fragmentatsiya", "Partenogenez", "Shizogoniya"], answer: "Kurtaklanish" },
        { question: "Nerv tizimining funksional birligi nima?", options: ["Neyron", "Neyrogliya", "Akson", "Sinaps"], answer: "Neyron" },
        { question: "Simbioz munosabatga eng yorqin misol bo'lgan, suv o'tlari va zamburug'lar birikmasidan hosil bo'lgan organizm qaysi?", options: ["Yo'sin", "Termit", "Lishaynik (Soya)", "Plun"], answer: "Lishaynik (Soya)" }
      ]
    },
    kimyo: {
      oson: [
        { question: "Suvning kimyoviy formulasi qaysi?", options: ["CO2", "H2O", "NaCl", "O2"], answer: "H2O" },
        { question: "Kislorodning kimyoviy belgisi qanday?", options: ["K", "O", "C", "H"], answer: "O" },
        { question: "Osh tuzining kimyoviy nomi nima?", options: ["Kaliy xlorid", "Natriy xlorid", "Kalsiy karbonat", "Azot kislotasi"], answer: "Natriy xlorid" },
        { question: "Kimyoviy elementlarning davriy sistemasini yaratgan olim kim?", options: ["Lomonosov", "Mendeleyev", "Nobel", "Kyuri"], answer: "Mendeleyev" },
        { question: "Vodorod elementi davriy jadvalda nechanchi tartib raqamda turadi?", options: ["1", "2", "6", "8"], answer: "1" },
        { question: "Eng engil gaz qaysi?", options: ["Kislorod", "Azot", "Vodorod", "Geliy"], answer: "Vodorod" },
        { question: "Karbonat angidrid gazi qaysi formula bilan ifodalanadi?", options: ["CO", "CO2", "CH4", "O3"], answer: "CO2" },
        { question: "Atom markazida nima joylashgan?", options: ["Elektron", "Yadro", "Molekula", "Ion"], answer: "Yadro" },
        { question: "Temir elementining kimyoviy belgisi qaysi?", options: ["F", "Fe", "I", "Cu"], answer: "Fe" },
        { question: "Oltin elementining kimyoviy belgisi qaysi?", options: ["Ag", "Au", "Al", "Pt"], answer: "Au" }
      ],
      orta: [
        { question: "Avogadro sonining qiymati nechaga teng?", options: ["6.02 * 10^23", "3.14", "9.81", "1.6 * 10^-19"], answer: "6.02 * 10^23" },
        { question: "Neytral muhitda pH ko'rsatkichi nechaga teng bo'ladi?", options: ["0", "7", "14", "5"], answer: "7" },
        { question: "Sulfat kislotaning formulasini toping.", options: ["HCl", "HNO3", "H2SO4", "H3PO4"], answer: "H2SO4" },
        { question: "Eng oddiy organik birikma - metan gazining formulasi qaysi?", options: ["CH4", "C2H6", "C2H2", "C3H8"], answer: "CH4" },
        { question: "Olmos va grafit bitta elementning allotropik shakli hisoblanadi. Bu qaysi element?", options: ["Kremniy", "Uglerod", "Azot", "Fosfor"], answer: "Uglerod" },
        { question: "Kovalent qutbsiz bog'lanishga ega molekulani ko'rsating.", options: ["HCl", "H2O", "H2", "NaCl"], answer: "H2" },
        { question: "Oddiy sharoitda yagona suyuq metall qaysi?", options: ["Simob (Hg)", "Brom (Br)", "Natriy (Na)", "Kaliy (K)"], answer: "Simob (Hg)" },
        { question: "Alkanlar umumiy formulasini ko'rsating.", options: ["CnH2n", "CnH2n+2", "CnH2n-2", "CnH2n-6"], answer: "CnH2n+2" },
        { question: "Havoning taxminan 78 foizini qaysi gaz tashkil qiladi?", options: ["Kislorod", "Azot", "Karbonat angidrid", "Argon"], answer: "Azot" },
        { question: "Kumush elementining kimyoviy belgisi qaysi?", options: ["Au", "Ag", "Cu", "Si"], answer: "Ag" }
      ],
      qiyin: [
        { question: "Gess qonunining asosiy mazmuni nimada?", options: ["Reaksiya tezligi konsentratsiyaga bog'liq", "Reaksiyaning issiqlik effekti jarayonning bosqichlariga emas, boshlang'ich va yakuniy holatiga bog'liqligi", "Eruvchanlik haroratga bog'liq", "Gaz hajmi bosimga teskari proporsional"], answer: "Reaksiyaning issiqlik effekti jarayonning bosqichlariga emas, boshlang'ich va yakuniy holatiga bog'liqligi" },
        { question: "Benzol molekulasidagi uglerod atomlari qaysi gibridlanish holatida bo'ladi?", options: ["sp", "sp2", "sp3", "sp3d"], answer: "sp2" },
        { question: "Elektroliz paytida katodda qanday jarayon sodir bo'ladi?", options: ["Oksidlanish", "Qaytarilish", "Neytrallanish", "Dissotsilanish"], answer: "Qaytarilish" },
        { question: "Kuchli elektrolitni ko'rsating.", options: ["H2O", "CH3COOH", "HCl", "NH4OH"], answer: "HCl" },
        { question: "Vodorod ko'rsatkichi pH = 3 bo'lgan eritmaning muhiti qanday?", options: ["Ishqoriy", "Neytral", "Kislotali", "Kuchsiz ishqoriy"], answer: "Kislotali" },
        { question: "Markovnikov qoidasiga ko'ra vodorod xlorid propen xlorlanganda vodorod qayerga birikadi?", options: ["Vodorodi ko'p bo'lgan uglerod atomiga", "Vodorodi kam bo'lgan uglerod atomiga", "Chekka uglerodga emas, o'rtadagiga", "Farqi yo'q"], answer: "Vodorodi ko'p bo'lgan uglerod atomiga" },
        { question: "Kaliy permanganat (KMnO4) tarkibida marganesning (Mn) oksidlanish darajasi nechaga teng?", options: ["+2", "+4", "+6", "+7"], answer: "+7" },
        { question: "Aluminiy gidroksid Al(OH)3 qanday xossaga ega?", options: ["Faqat kislotali", "Faqat asosli", "Amfoter (ham kislota, ham asos xossasi)", "Hech qanday xossaga ega emas"], answer: "Amfoter (ham kislota, ham asos xossasi)" },
        { question: "Tuzlarning suv ta'sirida parchalanish jarayoni nima deyiladi?", options: ["Elektroliz", "Gidroliz", "Gidratatsiya", "Kataliz"], answer: "Gidroliz" },
        { question: "Kimyoviy reaksiya tezligini o'zi sarflanmasdan tezlashtiradigan modda nima deyiladi?", options: ["Ingibitor", "Katalizator", "Indikator", "Erituvchi"], answer: "Katalizator" }
      ]
    },
    tarix: {
      oson: [
        { question: "Buyuk sarkarda, 'Kuch - adolatdadir' shiorini bayroq qilgan bobomiz kim?", options: ["Amir Temur", "Zahiriddin Muhammad Bobur", "Jaloliddin Manguberdi", "Mirzo Ulug'bek"], answer: "Amir Temur" },
        { question: "Ikkinchi jahon urushi qaysi yillarda bo'lib o'tgan?", options: ["1914-1918", "1939-1945", "1941-1945", "1917-1922"], answer: "1939-1945" },
        { question: "O'zbekiston Respublikasi o'z mustaqilligini qaysi yili qo'lga kiritgan?", options: ["1990-yil", "1991-yil", "1992-yil", "1993-yil"], answer: "1991-yil" },
        { question: "Eng qadimgi odamlar yashagan g'orlardan biri - Teshiktosh g'ori O'zbekistonning qaysi viloyatida joylashgan?", options: ["Qashqadaryo", "Surxondaryo", "Samarqand", "Buxoro"], answer: "Surxondaryo" },
        { question: "Qadimgi Misr hukmdorlari qanday nomlangan?", options: ["Xon", "Qirol", "Fir'avn", "Sulton"], answer: "Fir'avn" },
        { question: "Buyuk ipak yo'li qaysi davlatdan boshlangan?", options: ["Hindiston", "Xitoy", "Rim", "Eron"], answer: "Xitoy" },
        { question: "Hindistonda Boburiylar sulolasiga asos solgan shoh va shoir bobomiz kim?", options: ["Amir Temur", "Zahiriddin Muhammad Bobur", "Alisher Navoiy", "Mirzo Ulug'bek"], answer: "Zahiriddin Muhammad Bobur" },
        { question: "Dunyodagi etti mo'jizadan biri bo'lgan ulkan ehromlar (piramidalar) qaysi davlatda joylashgan?", options: ["Gretsiya", "Misr", "Italiya", "Mesopotamiya"], answer: "Misr" },
        { question: "Amir Temurning poytaxti qaysi shahar bo'lgan?", options: ["Toshkent", "Buxoro", "Samarqand", "Shahrisabz"], answer: "Samarqand" },
        { question: "Qadimgi Yunonistonda sport musobaqalari qanday nomlangan?", options: ["Gladiatorlik jangi", "Olimpiada o'yinlari", "Ritsarlar turniri", "Spartakiada"], answer: "Olimpiada o'yinlari" }
      ],
      orta: [
        { question: "Amir Temur va Boyazid Yildirim o'rtasidagi mashhur Anqara jangi qaysi yili sodir bo'lgan?", options: ["1370-yil", "1395-yil", "1402-yil", "1405-yil"], answer: "1402-yil" },
        { question: "Fransiyaning buyuk imperatori va sarkardasi Napoleon Bonapart qaysi jangda uzil-kesil mag'lub bo'lgan?", options: ["Borodino jangi", "Vaterloo jangi", "Austerlits jangi", "Leypsig jangi"], answer: "Vaterloo jangi" },
        { question: "Birinchi jahon urushining boshlanishiga qaysi voqea bahona bo'lgan?", options: ["Gersog Frans Ferdinandning Sarayevoda o'ldirilishi", "Polshaga hujum", "Kuba inqirozi", "Rimning qulashi"], answer: "Gersog Frans Ferdinandning Sarayevoda o'ldirilishi" },
        { question: "Qadimgi Rimda qullar va gladiatorlarning eng yirik qo'zg'oloniga kim rahbarlik qilgan?", options: ["Yuliy Sezar", "Spartak", "Gannibal", "Avgust"], answer: "Spartak" },
        { question: "Jaloliddin Manguberdi Chingizxon qo'shiniga qarshi qaysi daryo bo'yidagi jangda mardona kurashgan?", options: ["Sirdaryo", "Amudaryo", "Hind daryosi", "Yandzi daryosi"], answer: "Hind daryosi" },
        { question: "Movarounnahrda IX-X asrlarda hukmronlik qilgan, ilm-fan rivojlangan birinchi markazlashgan o'zbek sulolasi qaysi?", options: ["Qoraxoniylar", "Somoniylar", "G'aznaviylar", "Xorazmshohlar"], answer: "Somoniylar" },
        { question: "Amerika qit'asini 1492-yilda kashf etgan dengizchi sayyoh kim?", options: ["Vasko da Gama", "Xristofor Kolumb", "Magellan", "Amerigo Vespuchchi"], answer: "Xristofor Kolumb" },
        { question: "O'rta osiyolik buyuk munajjim va olim, Amir Temurning nabirasi kim?", options: ["Mirzo Ulug'bek", "Bobur", "Ali Qushchi", "Abu Ali ibn Sino"], answer: "Mirzo Ulug'bek" },
        { question: "AQSh mustaqillik deklaratsiyasi qaysi yili qabul qilingan?", options: ["1776-yil", "1789-yil", "1861-yil", "1492-yil"], answer: "1776-yil" },
        { question: "Xiva xonligida hukmronlik qilgan oxirgi sulola qaysi edi?", options: ["Qo'ng'irotlar", "Mang'itlar", "Minglar", "Shayboniylar"], answer: "Qo'ng'irotlar" }
      ],
      qiyin: [
        { question: "G'arbiy Rim imperiyasi qaysi yili butunlay parchalangan va qulagan?", options: ["395-yil", "476-yil", "1453-yil", "510-yil"], answer: "476-yil" },
        { question: "Miloddan avvalgi 530-yilda To'maris boshchiligidagi massagetlar qaysi Axamaniylar shohini mag'lub etib, boshini kesishgan?", options: ["Doro I", "Kir II", "Kserks", "Artakserks"], answer: "Kir II" },
        { question: "Buxoro amirligida hukmronlik qilgan oxirgi mang'it amiri kim edi?", options: ["Amir Nasrullo", "Amir Muzaffar", "Amir Sayyid Olimxon", "Amir Shohmurod"], answer: "Amir Sayyid Olimxon" },
        { question: "Yevropada O'ttiz yillik urushni yakunlab bergan va xalqaro munosabatlarning yangi tizimiga asos solgan 1648-yilgi tinchlik shartnomasi qanday nomlanadi?", options: ["Versal shartnomasi", "Vestfaliya tinchlik shartnomasi", "Utrext shartnomasi", "Vena kongressi"], answer: "Vestfaliya tinchlik shartnomasi" },
        { question: "Rossiya imperiyasi Toshkentni qaysi yili va kim boshchiligidagi qo'shin bilan bosib olgan?", options: ["1865-yil, general Chernyayev", "1873-yil, general Kaufman", "1868-yil, general Skobelev", "1860-yil, podsho Aleksandr"], answer: "1865-yil, general Chernyayev" },
        { question: "Qadimgi Afinada miloddan avvalgi 594-yilda juda muhim ijtimoiy-siyosiy islohotlar o'tkazgan qonunshunos kim?", options: ["Solon", "Perikl", "Drakon", "Likurg"], answer: "Solon" },
        { question: "Konstantinopol (Vizantiya poytaxti) Usmonlilar tomonidan bosib olingan va turklar poytaxtiga aylantirilgan yil?", options: ["1204-yil", "1389-yil", "1453-yil", "1517-yil"], answer: "1453-yil" },
        { question: "1916-yilda O'rta Osiyoda mardikorlikka olish farmoniga qarshi ko'tarilgan xalq qo'zg'oloni qayerda boshlangan?", options: ["Jizzaxda", "Xo'jandda", "Toshkentda", "Andijonda"], answer: "Xo'jandda" },
        { question: "Fransiyada Buyuk burjua inqilobi qaysi mashhur qal'aning shturm qilinishi bilan boshlangan?", options: ["Versal", "Bastiliya", "Luvr", "Tyuilri"], answer: "Bastiliya" },
        { question: "Arab xalifaligi davrida o'z xalifasiga qarshi Movarounnahrda ko'tarilgan 'Oq kiyimlilar' qo'zg'olonining rahbari kim edi?", options: ["Muqanna", "Behzod", "Sumbod", "Abu Muslim"], answer: "Muqanna" }
      ]
    },
    ingliztili: {
      oson: [
        { question: "Translate into English: 'Kitob'", options: ["Pen", "Book", "Notebook", "Chair"], answer: "Book" },
        { question: "Which word is a color?", options: ["Apple", "Red", "Run", "Happy"], answer: "Red" },
        { question: "Choose the correct pronoun: '___ am a teacher.'", options: ["He", "She", "I", "They"], answer: "I" },
        { question: "What is the plural form of 'Cat'?", options: ["Cats", "Cates", "Caties", "Mouse"], answer: "Cats" },
        { question: "What is the opposite of 'Big'?", options: ["Small", "Large", "Tall", "Heavy"], answer: "Small" },
        { question: "Complete the sentence: 'She ___ to school every day.'", options: ["go", "goes", "going", "gone"], answer: "goes" },
        { question: "What number is 'Ten'?", options: ["5", "10", "20", "1"], answer: "10" },
        { question: "How do you say 'Salom' in English?", options: ["Goodbye", "Thank you", "Hello", "Please"], answer: "Hello" },
        { question: "Which day comes after Monday?", options: ["Sunday", "Tuesday", "Wednesday", "Friday"], answer: "Tuesday" },
        { question: "What is the English word for 'Oila'?", options: ["Friend", "Family", "Brother", "Home"], answer: "Family" }
      ],
      orta: [
        { question: "Choose the correct past simple form: 'He ___ a letter yesterday.'", options: ["write", "wrote", "written", "writes"], answer: "wrote" },
        { question: "Identify the correct comparative form: 'Gold is ___ than silver.'", options: ["expensive", "more expensive", "most expensive", "expensiver"], answer: "more expensive" },
        { question: "Complete the sentence: 'If it rains tomorrow, we ___ at home.'", options: ["will stay", "stayed", "would stay", "stay"], answer: "will stay" },
        { question: "Which preposition is correct? 'I am interested ___ learning English.'", options: ["on", "at", "in", "for"], answer: "in" },
        { question: "What is the plural of 'Child'?", options: ["Childs", "Children", "Childrens", "Childes"], answer: "Children" },
        { question: "Choose the correct present perfect form: 'They ___ already finished the project.'", options: ["has", "have", "are", "did"], answer: "have" },
        { question: "What is the opposite of the word 'Generous'?", options: ["Kind", "Mean (Stingy)", "Polite", "Rich"], answer: "Mean (Stingy)" },
        { question: "Complete with the correct modal verb: 'You ___ touch that wire, it's dangerous!'", options: ["mustn't", "don't have to", "can", "needn't"], answer: "mustn't" },
        { question: "Select the correctly spelled word.", options: ["Beautifull", "Beautiful", "Butiful", "Beautifyl"], answer: "Beautiful" },
        { question: "What does the idiom 'Piece of cake' mean?", options: ["A slice of delicious dessert", "Something very easy to do", "A difficult choice", "To celebrate a birthday"], answer: "Something very easy to do" }
      ],
      qiyin: [
        { question: "Choose the correct inversion structure: 'Hardly ___ entered the room when the phone rang.'", options: ["he had", "had he", "he did", "did he"], answer: "had he" },
        { question: "Identify the meaning of the word 'Ubiquitous'.", options: ["Very rare", "Found everywhere", "Extremely dangerous", "Beautifully decorated"], answer: "Found everywhere" },
        { question: "Complete the Third Conditional sentence: 'If you ___ harder, you would have passed the exam.'", options: ["studied", "had studied", "would study", "have studied"], answer: "had studied" },
        { question: "Which passive structure is correct? 'The temple is said ___ built in the 12th century.'", options: ["to be", "to have been", "being", "having been"], answer: "to have been" },
        { question: "What is the synonym of 'Meticulous'?", options: ["Careless", "Thorough/Precise", "Aggressive", "Lazy"], answer: "Thorough/Precise" },
        { question: "Choose the correct gerund/infinitive form: 'He avoided ___ to the confrontation.'", options: ["to reply", "replying", "reply", "to replying"], answer: "replying" },
        { question: "What does the idiom 'Spill the beans' mean?", options: ["To cook dinner", "To reveal a secret accidentally", "To drop something on the floor", "To make a big mistake"], answer: "To reveal a secret accidentally" },
        { question: "Complete the sentence: 'The manager suggested that the meeting ___ postponed.'", options: ["be", "is", "was", "will be"], answer: "be" },
        { question: "Identify the antonym of 'Transient'.", options: ["Temporary", "Permanent", "Fleeting", "Short"], answer: "Permanent" },
        { question: "What is the grammatical term for the underlined part? 'Having finished her work, she went home.'", options: ["Gerund phrase", "Participle clause", "Infinitive of purpose", "Relative clause"], answer: "Participle clause" }
      ]
    },
    geografiya: {
      oson: [
        { question: "O'zbekiston Respublikasining poytaxti qaysi shahar?", options: ["Samarqand", "Buxoro", "Toshkent", "Andijon"], answer: "Toshkent" },
        { question: "Yer yuzida nechta materik (qizg'oq) bor?", options: ["4 ta", "5 ta", "6 ta", "7 ta"], answer: "6 ta" },
        { question: "Eng katta okean qaysi?", options: ["Atlantika okeani", "Tinch okeani", "Hind okeani", "Shimaliy muz okeani"], answer: "Tinch okeani" },
        { question: "Dunyodagi eng baland tog' cho'qqisi qaysi?", options: ["Kilimanjaro", "Everest (Jomolungma)", "Elbrus", "Alp"], answer: "Everest (Jomolungma)" },
        { question: "Yer sharining modeli nima deyiladi?", options: ["Xarita", "Globus", "Atlas", "Plan"], answer: "Globus" },
        { question: "Eng kichik materik qaysi?", options: ["Afrika", "Antarktida", "Avstraliya", "Yevropa"], answer: "Avstraliya" },
        { question: "Dunyodagi eng uzun daryolardan biri, Misrdan oqib o'tadigan daryo qaysi?", options: ["Amazonka", "Nil", "Volga", "Amudaryo"], answer: "Nil" },
        { question: "Qaysi davlat hududi bo'yicha dunyoda eng katta hisoblanadi?", options: ["Xitoy", "AQSh", "Rossiya", "Kanada"], answer: "Rossiya" },
        { question: "O'zbekistonning qaysi viloyati eng janubda joylashgan?", options: ["Xorazm", "Farg'ona", "Surxondaryo", "Toshkent"], answer: "Surxondaryo" },
        { question: "Kompasning ko'k (yoki qora) mili qaysi tomonni ko'rsatadi?", options: ["Shimol", "Janub", "Sharq", "G'arb"], answer: "Shimol" }
      ],
      orta: [
        { question: "Dunyodagi eng chuqur ko'l qaysi?", options: ["Kaspiy dengizi", "Baykal ko'li", "Viktoriya ko'li", "Orol dengizi"], answer: "Baykal ko'li" },
        { question: "Janubiy Amerikaning eng ulkan va sersuv daryosi qaysi?", options: ["Nil", "Amazonka", "Missisipi", "Kongo"], answer: "Amazonka" },
        { question: "Dunyodagi eng katta issiq sahro (cho'l) qaysi?", options: ["Gobi", "Kalahari", "Saxroi Kabir (Sahara)", "Qizilqum"], answer: "Saxroi Kabir (Sahara)" },
        { question: "Ekvator chizig'ining uzunligi taxminan necha kilometr?", options: ["20 000 km", "40 000 km", "60 000 km", "10 000 km"], answer: "40 000 km" },
        { question: "Yaponiya davlatining poytaxtini ko'rsating.", options: ["Pekin", "Seul", "Tokio", "Bangkok"], answer: "Tokio" },
        { question: "O'zbekiston hududining katta qismini qaysi cho'l egallagan?", options: ["Qoraqum", "Qizilqum", "Ustyurt", "Sahroi Kabir"], answer: "Qizilqum" },
        { question: "Dunyodagi eng ko'p aholiga ega bo'lgan (yoki yaqinda 1-o'ringa chiqqan) davlat qaysi?", options: ["Xitoy", "Hindiston", "AQSh", "Indoneziya"], answer: "Hindiston" },
        { question: "Buyuk Britaniya (London) orqali o'tadigan nolinchi meridian qanday nomlanadi?", options: ["Ekvator", "Grinvich meridiani", "Tropik chizig'i", "Paralell"], answer: "Grinvich meridiani" },
        { question: "Avstraliyaning poytaxti qaysi shahar?", options: ["Sidney", "Melburn", "Kanberra", "Vellington"], answer: "Kanberra" },
        { question: "Atmosferaning eng pastki, bulutlar va ob-havo hodisalari sodir bo'ladigan qatlami nima deyiladi?", options: ["Stratosfera", "Troposfera", "Mezosfera", "Termosfera"], answer: "Troposfera" }
      ],
      qiyin: [
        { question: "Dunyodagi eng baland sharshara - Anxel (Angel) qaysi davlatda joylashgan?", options: ["Braziliya", "Venesuela", "AQSh", "Janubiy Afrika"], answer: "Venesuela" },
        { question: "Dunyoning okeanga chiqish imkoniyati bo'lmagan, faqatgina okeanga chiqa olmaydigan davlatlar bilan o'ralgan (Double-landlocked) ikki davlatidan biri O'zbekiston bo'lsa, ikkinchisi qaysi?", options: ["Mo'g'uliston", "Lixtenshteyn", "Shveysariya", "Andorra"], answer: "Lixtenshteyn" },
        { question: "Shimoliy va Janubiy Amerikani ajratib turuvchi, Tinch va Atlantika okeanlarini bog'laydigan sun'iy kanal qaysi?", options: ["Suvaysh kanali", "Panama kanali", "Kil kanali", "Korinf kanali"], answer: "Panama kanali" },
        { question: "Yer po'stining gorizontal harakatlari va plitalar to'qnashuvi natijasida hosil bo'lgan tog'lar qanday ataladi?", options: ["Vulkanik tog'lar", "Burmali tog'lar (Skladchatie)", "Palaxsa tog'lar", "Erozion tog'lar"], answer: "Burmali tog'lar (Skladchatie)" },
        { question: "Islandiya orolida joylashgan, 2010-yilda otilib, butun Yevropa aviatsiyasini to'xtatib qo'ygan mashhur vulqon nomi?", options: ["Vezuviy", "Eyjafjallajökull", "Krakatau", "Fudziyama"], answer: "Eyjafjallajökull" },
        { question: "Dunyo okeanining eng chuqur nuqtasi - Mariana botig'ining chuqurligi taxminan qancha?", options: ["8 848 metr", "11 022 metr", "5 000 metr", "15 000 metr"], answer: "11 022 metr" },
        { question: "Afrika materigining eng g'arbiy chekka nuqtasi (musi) qanday nomlanadi?", options: ["Almadi burni", "Igna burni", "Yashil burun (Verde)", "Ras-Xafun"], answer: "Almadi burni" },
        { question: "Litosfera plitalarining bir-biridan uzoqlashishi (ajralishi) chegaralari ilm-fanda nima deyiladi?", options: ["Konvergent chegara", "Divergent chegara", "Transform chegara", "Subduksiya zonasi"], answer: "Divergent chegara" },
        { question: "Kanada davlatining poytaxti qaysi shahar?", options: ["Toronto", "Vankuver", "Ottava", "Monreal"], answer: "Ottava" },
        { question: "Dunyo bo'yicha eng ko'p vaqt mintaqalariga (Time zones) ega bo'lgan davlat (o'zining dengiz orti hududlari bilan birga) qaysi?", options: ["Rossiya", "AQSh", "Fransiya", "Xitoy"], answer: "Fransiya" }
      ]
    }
  }
 // ========================================================
  // 2. FLASHCARD SAVOLLARI (Savol va orqasidagi Javob)
  // ========================================================
  flashcard: {
    fizika: [
      { question: "Nyutonning 2-qonuni formulasi?", answer: "F = m * a" },
      { question: "Zichlik birligi nima?", answer: "kg/m³" },
      { question: "Bosim formulasi qanday?", answer: "P = F / S" },
      { question: "Tezlanish qaysi harf bilan belgilanadi?", answer: "a" },
      { question: "Elektr zaryadi birligi nima?", answer: "Kulon (C)" },
      { question: "Tok kuchi qaysi asbob bilan o'lchanadi?", answer: "Ampermetr" },
      { question: "Potensial energiya formulasi?", answer: "E_p = m * g * h" },
      { question: "Yorug'likning vakuumdagi tezligi qancha?", answer: "300 000 km/s" },
      { question: "Kuchlanish birligi nima?", answer: "Volt (V)" },
      { question: "O'tkazgich qarshiligi birligi nima?", answer: "Om (Ω)" },
      { question: "Chastota o'lchov birligi nima?", answer: "Gers (Hz)" },
      { question: "Jismning harakat miqdori (impuls) formulasi?", answer: "p = m * v" },
      { question: "Suyuqliklar bosimini o'lchovchi asbob?", answer: "Manometr" },
      { question: "Atmosfera bosimini o'lchovchi asbob?", answer: "Barometr" },
      { question: "Guk qonunining matematik ifodasi?", answer: "F = -k * x" },
      { question: "Mexanik ish formulasi qanday?", answer: "A = F * s" },
      { question: "Quvvat birligi nima?", answer: "Vatt (W)" },
      { question: "Issiqlik miqdori birligi nima?", answer: "Joul (J)" },
      { question: "Yorug'lik kuchi birligi nima?", answer: "Kandela (cd)" },
      { question: "Suyuqlik yuzasining taranglik koeffitsiyenti birligi?", answer: "N/m" },
      { question: "Havo namligini o'lchaydigan asbob?", answer: "Psixrometr (Gigrometr)" },
      { question: "Universal gaz doimiysi (R) ning qiymati?", answer: "8.31 J/(mol*K)" },
      { question: "Elektr sig'imi o'lchov birligi nima?", answer: "Farad (F)" },
      { question: "Magnit induksiyasi birligi nima?", answer: "Tesla (T)" },
      { question: "Yorug'lik oqimi o'lchov birligi nima?", answer: "Lyumen (lm)" }
    ],
    matematika: [
      { question: "Kvadratning yuzi formulasi?", answer: "S = a²" },
      { question: "To'g'ri to'rtburchak perimetri formulasi?", answer: "P = 2 * (a + b)" },
      { question: "Aylana uzunligi formulasi?", answer: "L = 2 * pi * r" },
      { question: "Pifagor teoremasi ifodasi?", answer: "a² + b² = c²" },
      { question: "Doira yuzi formulasi?", answer: "S = pi * r²" },
      { question: "Trapeziya yuzi formulasi?", answer: "S = ((a + b) / 2) * h" },
      { question: "Kubning hajmi formulasi?", answer: "V = a³" },
      { question: "Kvadrat tenglamaning umumiy ko'rinishi?", answer: "ax² + bx + c = 0" },
      { question: "sin(x) funksiyaning hosilasi nima?", answer: "cos(x)" },
      { question: "cos(x) funksiyaning hosilasi nima?", answer: "-sin(x)" },
      { question: "0! (nol faktorial) nimaga teng?", answer: "1" },
      { question: "log_a(a) ifodaning qiymati nechaga teng?", answer: "1" },
      { question: "Chiziqli funksiyaning umumiy formulasi?", answer: "y = kx + b" },
      { question: "Uchburchak yuzi (asos va balandlik orqali)?", answer: "S = (1/2) * a * h" },
      { question: "Paralellogramm yuzi formulasi?", answer: "S = a * h" },
      { question: "Yettining kubi (7³) nechaga teng?", answer: "343" },
      { question: "Eng kichik ikki xonali tub son qaysi?", answer: "11" },
      { question: "Sferaning sirt yuzi formulasi?", answer: "S = 4 * pi * r²" },
      { question: "Silindr hajmi formulasi?", answer: "V = pi * r² * h" },
      { question: "Konus hajmi formulasi?", answer: "V = (1/3) * pi * r² * h" },
      { question: "Yig'indining kvadrati (a + b)² formulasi?", answer: "a² + 2ab + b²" },
      { question: "Kvadratlar ayirmasi (a² - b²) formulasi?", answer: "(a - b)(a + b)" },
      { question: "Aylana yoyining burchak o'lchovi jami necha gradus?", answer: "360°" },
      { question: "tan(x) ning sin(x) va cos(x) orqali ifodasi?", answer: "sin(x) / cos(x)" },
      { question: "ln(e) ning qiymati nechaga teng?", answer: "1" }
    ],
    informatika: [
      { question: "Kompyuter drayveri nima?", answer: "Qurilmalarni OS bilan bog'lovchi dastur" },
      { question: "1 Megabayt necha Kilobaytga teng?", answer: "1024 KB" },
      { question: "WWW qisqartmasining kengaytmasi nima?", answer: "World Wide Web" },
      { question: "HTTP nima?", options: [], answer: "Gipermatn uzatish protokoli" },
      { question: "RAM qanday xotira hisoblanadi?", answer: "Tezkor (vaqtinchalik) xotira" },
      { question: "ROM qanday xotira hisoblanadi?", answer: "Doimiy (faqat o'qiladigan) xotira" },
      { question: "HTMLda havola (ssilka) yaratish tegi qaysi?", answer: "<a> tegi" },
      { question: "HTMLda rasm joylashtirish tegi qaysi?", answer: "<img> tegi" },
      { question: "Python-da satr (matn) turi qanday nomlanadi?", answer: "str" },
      { question: "Python-da butun son turi qanday nomlanadi?", answer: "int" },
      { question: "CSS qisqartmasining ma'nosi nima?", answer: "Cascading Style Sheets" },
      { question: "SQL nima?", answer: "Ma'lumotlar bazasi bilan ishlash tili" },
      { question: "Axborot xavfsizligining 3 tamoyili?", answer: "Yaxlitlik, Maxfiylik, Foydalana olishlik" },
      { question: "IP manzil necha bitdan iborat (IPv4)?", answer: "32 bit" },
      { question: "Klaviatura va sichqoncha qanday qurilma?", answer: "Kiritish qurilmasi" },
      { question: "Monitor va printer qanday qurilma?", answer: "Chiqarish qurilmasi" },
      { question: "Faylni butunlay o'chirish tezkor tugmalari?", answer: "Shift + Delete" },
      { question: "Oynani yopish tezkor tugmalari (Windows)?", answer: "Alt + F4" },
      { question: "Ma'lumotni izlash tezkor tugmalari?", answer: "Ctrl + F" },
      { question: "Eng mashhur ochiq kodli (open-source) OS qaysi?", answer: "Linux" },
      { question: "Almashish buferiga joylash (Vistavit) tugmalari?", answer: "Ctrl + V" },
      { question: "Algoritmning asosiy 3 ta turi qaysilar?", answer: "Chiziqli, Tarmoqlanuvchi, Takrorlanuvchi" },
      { question: "Kompyuter tarmog'ining eng kichik turi?", answer: "PAN (Personal Area Network)" },
      { question: "Sayt piktogrammasi (kichik belgisi) nima deyiladi?", answer: "Favicon" },
      { question: "Ma'lumotni zichlovchi dasturlar nima deyiladi?", answer: "Arxivatorlar (WinRAR, 7-Zip)" }
    ],
    biologiya: [
      { question: "Hujayra nazariyasi asoschilari kimlar?", answer: "Shleyden va Shvann" },
      { question: "Hujayra ichidagi rangsiz quyuq suyuqlik?", answer: "Sitoplazma" },
      { question: "O'simlik hujayrasi devori nimadan iborat?", answer: "Sellyuloza (Kletchatka)" },
      { question: "Baliqlarning yuragi necha kamerali?", answer: "2 kamerali" },
      { question: "Sudralib yuruvchilar yuragi necha kamerali?", answer: "3 kamerali (chala to'siqli)" },
      { question: "Sutemizuvchilar va qushlar yuragi necha kamerali?", answer: "4 kamerali" },
      { question: "DNK tarkibidagi 4 ta nukleotid nomi?", answer: "Adenin, Timin, Guanin, Sitozin" },
      { question: "Inson tanasidagi eng uzun suyak qaysi?", answer: "Comb suyak (Comb suyagi)" },
      { question: "Odamda nechta juft qovurg'a bor?", answer: "12 juft (24 ta)" },
      { question: "Zamburug'lar hujayra devori nimadan iborat?", answer: "Xitin" },
      { question: "Inson miyasining eng katta qismi?", answer: "Katta yarim sharlar po'stlog'i" },
      { question: "Qonning suyuq qismi nima deyiladi?", answer: "Plazma" },
      { question: "Oq qon hujayralarining nomi nima?", answer: "Leykotsitlar" },
      { question: "Qon laxtalanishini ta'minlovchi hujayralar?", answer: "Trombotsitlar" },
      { question: "Bakteriofag nima?", answer: "Bakteriyalarni yemiruvchi virus" },
      { question: "Gidra qaysi tipga mansub organizm?", answer: "Kavakichlilarlar tipi" },
      { question: "Inson tanasidagi eng katta ichki a'zo?", answer: "Jigar" },
      { question: "Ko'zning rangdor pardasi markazidagi teshik?", answer: "Qorachiq" },
      { question: "Nafas olish markazi miyaning qaysi qismida?", answer: "Uzunchoq miyada" },
      { question: "Ildizning eng uchi qanday himoyalangan?", answer: "Ildiz qinchasi bilan" },
      { question: "Hujayra yadrosini birinchi bo'lib kashf etgan kim?", options: [], answer: "Robert Braun" },
      { question: "Eshiting, qon aylanish tizimini kim kashf etgan?", answer: "Uilyam Garvey" },
      { question: "Faqat ona orqali bolaga o'tadigan organoid irsiyati?", answer: "Mitoxondrial irsiyat" },
      { question: "O'simliklarda changlanishdan keyin nima sodir bo'ladi?", answer: "Urug'lanish" },
      { question: "Tirik organizmlarning bir-biri bilan aloqasini o'rganuvchi fan?", answer: "Ekologiya" }
    ],
    kimyo: [
      { question: "Suv tarkibidagi vodorod va kislorod nisbati?", answer: "2 : 1" },
      { question: "Atomning zaryadsiz zarrachasi nima?", answer: "Neytron" },
      { question: "Atomning musbat zaryadli zarrachasi nima?", answer: "Proton" },
      { question: "Atomning manfiy zaryadli zarrachasi nima?", answer: "Elektron" },
      { question: "Mendeleyev jadvalidagi 7-element qaysi?", answer: "Azot (N)" },
      { question: "Ozon gazining kimyoviy formulasi qaysi?", answer: "O3" },
      { question: "Eritma muhitini aniqlovchi moddalar?", answer: "Indikatorlar (Litmus, Fenolftalein)" },
      { question: "Eng aktiv metall qaysi?", answer: "Seziy (Cs)" },
      { question: "Eng aktiv nemetall qaysi?", answer: "Ftor (F)" },
      { question: "Oddiy sharoitda yagona suyuq nemetall qaysi?", answer: "Brom (Br)" },
      { question: "Alkinlar sinfining birinchi vakili qaysi?", answer: "Atsetilen (C2H2)" },
      { question: "Marmar va bo'rning kimyoviy formulasi?", answer: "CaCO3" },
      { question: "Gidroksoniy ionining formulasi qanday?", answer: "H3O+" },
      { question: "Oksidlanish darajasi pasayishi jarayoni nima?", answer: "Qaytarilish" },
      { question: "Oksidlanish darajasi ortishi jarayoni nima?", answer: "Oksidlanish" },
      { question: "Vodorod peroksidning formulasi qanday?", answer: "H2O2" },
      { question: "Ammiak gazining kimyoviy formulasi qaysi?", answer: "NH3" },
      { question: "Organik kimyo qaysi element birikmalarini o'rganadi?", answer: "Uglerod (C)" },
      { question: "Oddiy sharoitda gaz holatdagi galogenlar?", answer: "Ftor va Xlor" },
      { question: "Tuz kislotasining kimyoviy formulasi qaysi?", answer: "HCl" },
      { question: "Is gazining kimyoviy formulasi qaysi?", answer: "CO" },
      { question: "Glaytsin qaysi sinfga mansub birikma?", answer: "Aminokislotalar" },
      { question: "Erituvchining 1 litridagi erigan modda mollari soni?", answer: "Molyar konsentratsiya" },
      { question: "Kumush ko'zgu reaksiyasini beradigan organik moddalar?", answer: "Aldegidlar" },
      { question: "Po'lat nima va nimalarning qotishmasi?", answer: "Temir va Uglerod qotishmasi" }
    ],
    tarix: [
      { question: "Amir Temur tug'ilgan yil va joy?", answer: "1336-yil, Xoja Ilg'or (Yakkabog')" },
      { question: "Avesto kitobi qaysi dinga tegishli?", answer: "Zardushtiylik" },
      { question: "Eski va Yangi dunyoni bog'lagan qadimgi yo'l?", answer: "Buyuk Ipak Yo'li" },
      { question: "Mirzo Ulug'bek qurdirgan mashhur rasadxona qayerda?", answer: "Samarqandda" },
      { question: "Birinchi jahon urushi qachon boshlangan?", answer: "1914-yil" },
      { question: "O'zbekiston Respublikasi Konstitutsiyasi qabul qilingan kun?", answer: "8-dekabr" },
      { question: "Qadimgi dunyoning eng yirik kutubxonasi qayerda bo'lgan?", answer: "Aleksandriyada" },
      { question: "Rim davlatiga asos solgan aka-uka kimlar?", answer: "Romul va Rem" },
      { question: "Jaloliddin Manguberdining otasi kim edi?", answer: "Muhammad Xorazmshoh" },
      { question: "Buyuk fransuz inqilobi qaysi yili sodir bo'lgan?", answer: "1789-yil" },
      { question: "Buxoro xonligiga asos solgan o'zbek sulolasi?", answer: "Shayboniylar" },
      { question: "Jadidchilik harakatining Turkistondagi yetakchisi kim?", answer: "Mahmudxo'ja Behbudiy" },
      { question: "Al-Xorazmiy qaysi mashhur ilm markaziga rahbarlik qilgan?", answer: "Baytul Hikma (Bag'dod)" },
      { question: "Shohrux Mirzoning poytaxti qaysi shahar bo'lgan?", options: [], answer: "Hirot" },
      { question: "Toshkent shahri necha yillik yubileyini nishonlagan?", answer: "2200 yillik" },
      { question: "Qadimgi Bobilning eng mashhur qonun chiqaruvchi shohi?", answer: "Xammurapi" },
      { question: "G'aznaviylar davlatining eng qudratli hukmdori?", answer: "Sulton Mahmud G'aznaviy" },
      { question: "Rossiyada krepostnoylik huquqi qaysi yili bekor qilingan?", answer: "1861-yil" },
      { question: "Qo'qon xonligidagi oxirgi mustaqil hukmdor kim?", answer: "Xudoyorxon" },
      { question: "Turkiston Muxtoriyati qachon tashkil etilgan?", answer: "1917-yil noyabr" },
      { question: "Napoleonning yakuniy surgun qilingan oroli nomi?", answer: "Muqaddas Yelena oroli" },
      { question: "Doro I ga qarshi kurashgan sak cho'poni kim?", answer: "Shiroq" },
      { question: "Miyona (Afrosiyob) mudofaasida kim mardlik ko'rsatgan?", answer: "Spitamen" },
      { question: "Amir Temurning eng oxirgi harbiy yurishi qaysi davlatga edi?", answer: "Xitoyga" },
      { question: "Birlashgan Millatlar Tashkiloti (BMT) tuzilgan yil?", answer: "1945-yil" }
    ],
    ingliztili: [
      { question: "What is the past simple of 'Go'?", answer: "went" },
      { question: "What is the past participle (V3) of 'Eat'?", answer: "eaten" },
      { question: "What is the opposite of 'Dark'?", answer: "Light / Bright" },
      { question: "Synonym of the word 'Fast'?", answer: "Quick / Rapid" },
      { question: "Which suffix makes 'Happy' a noun?", answer: "-ness (Happiness)" },
      { question: "Plural form of the word 'Tooth'?", answer: "teeth" },
      { question: "Plural form of the word 'Mouse'?", answer: "mice" },
      { question: "What is the negative form of 'must'?", answer: "mustnot / mustn't" },
      { question: "Complete the idiom: 'Break a ___' (Good luck)", answer: "leg" },
      { question: "Comparative form of the adjective 'Bad'?", answer: "worse" },
      { question: "Superlative form of the adjective 'Good'?", answer: "the best" },
      { question: "Which preposition goes with 'depend'?", answer: "on / upon" },
      { question: "Which preposition goes with 'afraid'?", answer: "of" },
      { question: "What tense is 'I have been working'?", answer: "Present Perfect Continuous" },
      { question: "Antonym of the word 'Arrive'?", answer: "Depart / Leave" },
      { question: "A person who flies a plane is a ___.", answer: "pilot" },
      { question: "The capital city of the USA?", answer: "Washington, D.C." },
      { question: "How many letters are there in the English alphabet?", answer: "26 letters" },
      { question: "Past continuous form of 'She sings'?", answer: "She was singing" },
      { question: "What does 'CEO' stand for?", answer: "Chief Executive Officer" },
      { question: "Synonym of 'Beautiful' beginning with 'G'?", answer: "Gorgeous" },
      { question: "The structure 'used to' indicates what?", answer: "Past habits" },
      { question: "Opposite of the adjective 'Polite'?", answer: "Impolite / Rude" },
      { question: "What do you call a baby dog?", answer: "puppy" },
      { question: "Which modal verb represents 100% certainty in the past?", answer: "must have + V3" }
    ],
    geografiya: [
      { question: "Eng katta materik qaysi?", answer: "Evroosiyo" },
      { question: "Dunyodagi eng uzun tog' tizmasi qaysi?", answer: "And tog'lari" },
      { question: "O'zbekiston chegaradosh bo'lgan eng uzun davlat?", answer: "Qozog'iston" },
      { question: "Eng kichik okean qaysi?", answer: "Shimoliy muz okeani" },
      { question: "Dunyodagi eng baland sharshara?", answer: "Anxel" },
      { question: "Eng ko'p davlat bilan chegaradosh mamlakat?", answer: "Xitoy (va Rossiya - 14 tadan)" },
      { question: "Afrika materigining eng baland nuqtasi?", answer: "Kilimanjaro vulqoni" },
      { question: "Dunyoning eng yirik oroli qaysi?", answer: "Grenlandiya" },
      { question: "Shimoliy Amerikaning eng katta daryosi?", answer: "Missisipi" },
      { question: "O'zbekiston hududi maydoni qancha?", answer: "448.9 ming km²" },
      { question: "Yer po'stining eng qalin qismi qayerda?", answer: "Tog'lar ostida" },
      { question: "Yer sharining markaziy qismi nima deyiladi?", answer: "Yadro" },
      { question: "Avstraliyadagi eng uzun daryo tizimi?", answer: "Murrey va Darling" },
      { question: "Buyuk Britaniyaning poytaxti qaysi shahar?", answer: "London" },
      { question: "Janubiy qutbda joylashgan materik nomi?", answer: "Antarktida" },
      { question: "Fransiyaning poytaxti qaysi shahar?", answer: "Parij" },
      { question: "Italiya poytaxti qaysi shahar?", answer: "Rim" },
      { question: "Yer o'z o'qi atrofida qaysi tomondan qaysi tomonga aylanadi?", answer: "G'arbdan Sharqqa" },
      { question: "Vulkan og'zidagi voronkasimon chuqurlik?", answer: "Krater" },
      { question: "Dunyodagi eng sersuv va yirik havzali daryo?", answer: "Amazonka" },
      { question: "Misr poytaxti qaysi shahar?", answer: "Qohira" },
      { question: "Turkiya davlatining poytaxti qaysi shahar?", answer: "Anqara" },
      { question: "Okean suvining eng yuqori ko'tarilishi nima deyiladi?", answer: "To'lqin (Mavj / Tsunami emas, Priliv)" },
      { question: "Yerning havo qobig'i qanday nomlanadi?", answer: "Atmosfera" },
      { question: "Dunyoda eng katta yarim orol qaysi?", answer: "Arabiston yarim oroli" }
    ]
  }

 // ========================================================
  // 3. TEZKOR JAVOB SAVOLLARI (Tezkor yoziladigan aniq javoblar)
  // ========================================================
  tezkor: {
    matematika: [
      { question: "5 * 5 nechaga teng?", answer: "25" },
      { question: "121 ning ildizi nechaga teng?", answer: "11" },
      { question: "15 ning kvadrati nechaga teng?", answer: "225" },
      { question: "Eng kichik tub son?", answer: "2" },
      { question: "Uchburchak ichki burchaklari yig'indisi necha gradus?", answer: "180" },
      { question: "To'g'ri burchak necha gradusga teng?", answer: "90" },
      { question: "0.5 sonining kasr ko'rinishidagi maxraji qaysi son?", answer: "2" },
      { question: "Doira to'liq burchagi necha gradus?", answer: "360" },
      { question: "Yigirma birdan keyingi tub son qaysi?", answer: "23" },
      { question: "Nol faktorial (0!) nimaga teng?", answer: "1" },
      { question: "100 ning 15 foizi nechaga teng?", answer: "15" },
      { question: "2 ning beshinchi darajasi (2^5) nechaga teng?", answer: "32" },
      { question: "3 ning kubi nechaga teng?", answer: "27" },
      { question: "64 sonining kub ildizi nechaga teng?", answer: "4" },
      { question: "40 ning yarmining yarmi nechaga teng?", answer: "10" },
      { question: "Sonni nolga bo'lish mumkinmi? (ha yoki yo'q)", answer: "yo'q" },
      { question: "10 ning kvadratiga 24 ni qo'shsa necha bo'ladi?", answer: "124" },
      { question: "7 ning kvadrati nechaga teng?", answer: "49" },
      { question: "Teng tomonli uchburchakning bir burchagi necha gradus?", answer: "60" },
      { question: "Kvadratning necha foizi uning choragiga teng?", answer: "25" },
      { question: "Sonning yuzdan bir qismi nima deyiladi?", answer: "foiz" },
      { question: "9 ning kvadrat ildizi nechaga teng?", answer: "3" },
      { question: "1000 sonida nechta nol bor?", answer: "3" },
      { question: "Sirt yuzaga ega bo'lmagan, faqat o'ringa ega geometrik shakl?", answer: "nuqta" },
      { question: "Yetti burchakning nechta tomoni bor?", answer: "7" },
      { question: "Eng kichik uch xonali son?", answer: "100" },
      { question: "50 ning 20 foizi nechaga teng?", answer: "10" },
      { question: "81 sonining kvadrat ildizi?", answer: "9" },
      { question: "Kvadrat tomoni 5 bo'lsa, perimetri nechaga teng?", answer: "20" },
      { question: "To'g'ri to'rtburchak bo'yi 4, eni 3 bo'lsa, yuzi nechaga teng?", answer: "12" },
      { question: "Yoy burchak necha gradusga teng?", answer: "180" },
      { question: "Bir soatda nechta minut bor?", answer: "60" },
      { question: "0.25 qaysi oddiy kasrga teng? (1/2, 1/4 yoki 1/3)", answer: "1/4" },
      { question: "90 dan katta, 180 dan kichik burchak turi?", answer: "o'tmas" },
      { question: "90 dan kichik burchak turi qanday nomlanadi?", answer: "o'tkir" },
      { question: "Eng katta ikki xonali juft son?", answer: "98" },
      { question: "2, 4, 6, 8 sonlar ketma-ketligi qanday sonlar?", answer: "juft" },
      { question: "Pifagor uchligiga ko'ra, katetlari 3 va 4 bo'lgan uchburchak gipotenuzasi?", answer: "5" },
      { question: "Kubning nechta uchi bor?", answer: "8" },
      { question: "Kubning nechta yoqi bor?", answer: "6" },
      { question: "Kubning nechta qirrasi bor?", answer: "12" },
      { question: "10 ning kubi nechaga teng?", answer: "1000" },
      { question: "169 sonining kvadrat ildizi nechaga teng?", answer: "13" },
      { question: "144 sonining kvadrat ildizi nechaga teng?", answer: "12" },
      { question: "6 ning kubi nechaga teng?", answer: "216" },
      { question: "O'ziga teskari songa teng bo'lgan musbat son?", answer: "1" },
      { question: "Har qanday sonning nolinchi darajasi nimaga teng?", answer: "1" },
      { question: "Yig'indini topish amali nima deyiladi?", answer: "qo'shish" },
      { question: "Ko'paytirish amalining natijasi nima deyiladi?", answer: "ko'paytma" },
      { question: "Bo'lish amalining natijasi nima deyiladi?", answer: "bo'linma" }
    ],
    fizika: [
      { question: "Kuchni o'lchaydigan asbob?", answer: "Dinamometr" },
      { question: "Tezlik birligi nima (SI sistemasida)? (m/s yoki km/soat)", answer: "m/s" },
      { question: "Kuch o'lchov birligi nima?", answer: "Nyuton" },
      { question: "Bosim o'lchov birligi nima?", answer: "Paskal" },
      { question: "Massa o'lchov birligi nima?", answer: "kilogramm" },
      { question: "Vaqt o'lchov birligi nima?", answer: "sekund" },
      { question: "Ish va energiya o'lchov birligi nima?", answer: "Joul" },
      { question: "Quvvat o'lchov birligi nima?", answer: "Vatt" },
      { question: "Elektr toki kuchi birligi nima?", answer: "Amper" },
      { question: "Elektr kuchlanishi birligi nima?", answer: "Volt" },
      { question: "Elektr qarshiligi birligi nima?", answer: "Om" },
      { question: "Chastota o'lchov birligi nima?", answer: "Gers" },
      { question: "Elektr zaryadi o'lchov birligi nima?", answer: "Kulon" },
      { question: "Atmosfera bosimini o'lchaydigan asbob?", answer: "Barometr" },
      { question: "Haroratni o'lchaydigan asbob?", answer: "Termometr" },
      { question: "Suyuqliklar zichligini o'lchovchi asbob?", answer: "Areometr" },
      { question: "Bosim formulasida kuch nimaga bo'linadi?", answer: "yuzaga" },
      { question: "Erkin tushish tezlanishi g ning qiymati taxminan nechaga teng?", answer: "10" },
      { question: "Suvning muzlash harorati necha gradus Selsiy?", answer: "0" },
      { question: "Suvning qaynash harorati necha gradus Selsiy?", answer: "100" },
      { question: "Elektr sig'imi birligi nima?", answer: "Farad" },
      { question: "Induktivlik o'lchov birligi nima?", answer: "Genri" },
      { question: "Magnit induksiyasi birligi nima?", answer: "Tesla" },
      { question: "Yorug'lik kuchi o'lchov birligi nima?", answer: "Kandela" },
      { question: "Tabiatdagi eng katta tezlik nima tezligi?", answer: "yorug'lik" },
      { question: "Ovoz vakuumda tarqaladimi? (ha yoki yo'q)", answer: "yo'q" },
      { question: "Moddaning nechta asosiy agregat holati bor?", answer: "4" },
      { question: "Doimiy temperaturada kechadigan jarayon?", answer: "izotermik" },
      { question: "Doimiy bosimda kechadigan jarayon?", answer: "izobarik" },
      { question: "Doimiy hajmda kechadigan jarayon?", answer: "izoxorik" },
      { question: "Nisbiylik nazariyasi asoschisi bo'lgan olim kim?", answer: "Eynshteyn" },
      { question: "Yerning tortishish kuchi tufayli jismlarga beradigan tezlanishi?", answer: "erkin tushish tezlanishi" },
      { question: "Yorug'likning to'siqlarni aylanib o'tish hodisasi?", answer: "difraksiya" },
      { question: "Yorug'lik to'lqinlarining qo'shilishidan hosil bo'ladigan hodisa?", answer: "interferensiya" },
      { question: "Kinetik energiya formulasida tezlikning nimasi olinadi?", answer: "kvadrati" },
      { question: "Atom markazida nima joylashgan?", answer: "yadro" },
      { question: "Yadro atrofida qaysi manfiy zarrachalar aylanadi?", answer: "elektronlar" },
      { question: "Yadro tarkibidagi musbat zaryadli zarracha?", answer: "proton" },
      { question: "Yadro tarkibidagi zaryadsiz zarracha?", answer: "neytron" },
      { question: "Havo namligini o'lchaydigan asbob?", answer: "psixrometr" },
      { question: "Tezlik o'zgarish tezligini ifodalovchi kattalik?", answer: "tezlanish" },
      { question: "Ishqalanish kuchi harakatga nisbatan qanday yo'naladi?", answer: "qarshi" },
      { question: "Kosinus nolda nechaga teng?", answer: "1" },
      { question: "Sinus nolda nechaga teng?", answer: "0" },
      { question: "Optik kuch birligi nima?", answer: "dioptriya" },
      { question: "Yorug'lik oqimi birligi nima?", answer: "lyumen" },
      { question: "Yoritilganlik birligi nima?", answer: "lyuks" },
      { question: "Issiqlik uzatishning modda ko'chmasdan kechadigan turi?", answer: "issiqo'tkazuvchanlik" },
      { question: "Suyuqlik va gaz oqimi orqali issiqlik uzatish turi?", answer: "konveksiya" },
      { question: "Quyoshdan Yerga issiqlik qaysi usulda keladi?", answer: "nurlanish" }
    ],
    informatika: [
      { question: "Axborotning eng kichik o'lchov birligi?", answer: "bit" },
      { question: "1 bayt nechta bitga teng?", answer: "8" },
      { question: "Kompyuterning asosiy hisoblash miyasi?", answer: "protsessor" },
      { question: "Vaqtinchalik tezkor xotira qisqartmasi?", answer: "RAM" },
      { question: "Doimiy xotira qisqartmasi nima?", answer: "ROM" },
      { question: "1 kilobayt nechta baytga teng?", answer: "1024" },
      { question: "1 megabayt nechta kilobaytga teng?", answer: "1024" },
      { question: "Matn yozish uchun ishlatiladigan eng mashhur MS dasturi?", answer: "Word" },
      { question: "Prezentatsiya tayyorlash uchun MS dasturi?", answer: "PowerPoint" },
      { question: "Elektron jadvallar bilan ishlash uchun MS dasturi?", answer: "Excel" },
      { question: "Internet sahifalarini ochuvchi dasturlar?", answer: "brauzer" },
      { question: "Google Chrome qanday dastur?", answer: "brauzer" },
      { question: "Kompyuterni viruslardan himoya qiluvchi dastur?", answer: "antivirus" },
      { question: "Fayllarni siqish va arxivlash dasturi?", answer: "arxivator" },
      { question: "Nusxa olish uchun tezkor tugmalar?", answer: "Ctrl+C" },
      { question: "Joylashtirish (vstavit) uchun tezkor tugmalar?", answer: "Ctrl+V" },
      { question: "Amalni bekor qilish (orqaga qaytarish) tugmalari?", answer: "Ctrl+Z" },
      { question: "Hujjatni saqlash (Soxranit) tezkor tugmalari?", answer: "Ctrl+S" },
      { question: "Faylni butunlay o'chirish tugmalari?", answer: "Shift+Delete" },
      { question: "Barcha elementlarni belgilash (Vydelit vse) tugmalari?", answer: "Ctrl+A" },
      { question: "Klaviatura qanday qurilma? (kiritish yoki chiqarish)", answer: "kiritish" },
      { question: "Monitor qanday qurilma? (kiritish yoki chiqarish)", answer: "chiqarish" },
      { question: "Printer qanday qurilma? (kiritish yoki chiqarish)", answer: "chiqarish" },
      { question: "Sichqoncha (mishka) qanday qurilma?", answer: "kiritish" },
      { question: "HTML nima? (dasturlash tili yoki belgilash tili)", answer: "belgilash tili" },
      { question: "Python nima? (dasturlash tili yoki operatsion tizim)", answer: "dasturlash tili" },
      { question: "Windows nima? (dasturlash tili yoki operatsion tizim)", answer: "operatsion tizim" },
      { question: "Linux qanday dasturiy ta'minot turi?", answer: "operatsion tizim" },
      { question: "Veb-sahifalarga dizayn va uslub beruvchi til?", answer: "CSS" },
      { question: "Ma'lumotlar bazasi bilan ishlash tili?", answer: "SQL" },
      { question: "Python-da ma'lumotni ekranga chiqarish buyrug'i?", answer: "print" },
      { question: "Python-da foydalanuvchidan ma'lumot olish buyrug'i?", answer: "input" },
      { question: "Ikklik sanoq sistemasida qaysi raqamlar ishlatiladi?", answer: "0 va 1" },
      { question: "Saytlar manzili boshida keladigan protokol?", answer: "http" },
      { question: "Butun dunyo kompyuter tarmog'i nima deyiladi?", answer: "internet" },
      { question: "Fayl nomidan keyin nuqtadan so'ng keladigan qism?", answer: "kengaytma" },
      { question: "Rasm fayllarining eng ko'p tarqalgan kengaytmasi?", answer: "jpg" },
      { question: "Bajariluvchi dastur fayllarining kengaytmasi?", answer: "exe" },
      { question: "Kompyuterning ishlash ketma-ketligi buyruqlari to'plami?", answer: "algoritm" },
      { question: "O'z-o'zini chaqiradigan funksiya nima deyiladi?", answer: "rekursiya" },
      { question: "Dasturdagi xatolarni topish va tuzatish jarayoni?", answer: "otladka" },
      { question: "IP manzillar necha qismdan iborat bo'ladi (IPv4)?", answer: "4" },
      { question: "Sayt piktogrammasi bo'lgan kichik rasmcha?", answer: "favicon" },
      { question: "Tarmoq qurilmalarini bog'lovchi simsiz texnologiya?", answer: "wi-fi" },
      { question: "Algoritmning grafik ko'rinishi qanday nomlanadi?", answer: "blok-suxema" },
      { question: "Axborotni shifrlash va himoya qilish fani?", answer: "kriptografiya" },
      { question: "Kompyuter darslarida chizish uchun mo'ljallangan dastur?", answer: "Paint" },
      { question: "Ochiq kodli eng mashhur operatsion tizim yadrosi?", answer: "Linux" },
      { question: "Loyiha versiyalarini boshqarish tizimi?", answer: "Git" },
      { question: "Kompyuter qurilmalarini OS bilan tanishtiruvchi dastur?", answer: "drayver" }
    ],
    biologiya: [
      { question: "Tirik organizmlarning eng kichik birligi?", answer: "hujayra" },
      { question: "Biologiya nimani o'rganadi?", answer: "hayotni" },
      { question: "O'simliklarni o'rganadigan fan?", answer: "botanika" },
      { question: "Hayvonlarni o'rganadigan fan?", answer: "zoologiya" },
      { question: "Qo'ziqorinlarni o'rganadigan fan?", answer: "mikologiya" },
      { question: "Bakteriyalarni o'rganadigan fan?", answer: "bakteriologiya" },
      { question: "O'simliklarga yashil rang beruvchi pigment?", answer: "xlorofill" },
      { question: "O'simliklarning quyosh nuri orqali oziqlanish jarayoni?", answer: "fotosintez" },
      { question: "Odam tanasining qon haydaydigan asosiy a'zosi?", answer: "yurak" },
      { question: "Inson o'pka orqali qaysi gazni yutadi?", answer: "kislorod" },
      { question: "Inson nafas chiqarganda qaysi gazni chiqaradi?", answer: "karbonat angidrid" },
      { question: "Hujayraning energetik stansiyasi?", answer: "mitoxondriya" },
      { question: "Hujayrada oqsil sintez qiladigan organoid?", answer: "ribosoma" },
      { question: "Hujayra markazi va irsiy axborot saqlanadigan joy?", answer: "yadro" },
      { question: "Inson tanasida nechta xromosoma bor?", answer: "46" },
      { question: "Inson tanasidagi xromosomalar nechta juftni tashkil etadi?", answer: "23" },
      { question: "Qon hujayralarining qizil turi nima deyiladi?", answer: "eritrotsitlar" },
      { question: "Qon hujayralarining oq turi nima deyiladi?", answer: "leykotsitlar" },
      { question: "Qon laxtalanishini ta'minlovchi hujayralar?", answer: "trombotsitlar" },
      { question: "Qon tarkibidagi temir moddasi tutgan oqsil?", answer: "gemoglobin" },
      { question: "Baliqlar nima orqali nafas oladi?", answer: "jabra" },
      { question: "Kit baliqmi yoki sutemizuvchi?", answer: "sutemizuvchi" },
      { question: "Dunyodagi eng katta sutemizuvchi hayvon?", answer: "ko'k kit" },
      { question: "Inson tanasidagi eng katta ichki a'zo?", answer: "jigar" },
      { question: "Nerv tizimining asosiy funksional hujayrasi?", answer: "neyron" },
      { question: "Genetika fanining otasi kim?", answer: "Mendel" },
      { question: "Evolutsiya nazariyasi asoschisi kim?", answer: "Darvin" },
      { question: "Hujayrani mikroskopda birinchi ko'rgan olim?", answer: "Guk" },
      { question: "Suv o'tlari va zamburug'lar simbiozidan hosil bo'lgan organizm?", answer: "lishaynik" },
      { question: "Organizmlarning tashqi muhitga moslashishi nima deyiladi?", answer: "adaptatsiya" },
      { question: "Irsiyatning tarkibiy va funksional birligi?", answer: "gen" },
      { question: "DNK dagi adenin nukleotidiga qaysi biri mos keladi?", answer: "timin" },
      { question: "Inson tanasida nechta qon guruhi bor?", answer: "4" },
      { question: "Zamburug'lar hujayra devori nimadan iborat?", answer: "xitin" },
      { question: "O'simliklar hujayra devori nimadan iborat?", answer: "sellyuloza" },
      { question: "Yurakdan a'zolarga qon tashiydigan tomirlar?", answer: "arteriyalar" },
      { question: "A'zolardan yurakka qon tashiydigan tomirlar?", answer: "venalar" },
      { question: "Eng mayda qon tomirlari qanday nomlanadi?", answer: "kapillyarlar" },
      { question: "Insulin gormonini qaysi bez ishlab chiqaradi?", answer: "me'da osti bezi" },
      { question: "Ko'zning eng ichki yorug'lik sezuvchi pardasi?", answer: "to'r parda" },
      { question: "Sudralib yuruvchilar yuragi necha kamerali?", answer: "3" },
      { question: "Qushlarning yuragi necha kamerali?", answer: "4" },
      { question: "Baliqlarning yuragi necha kamerali?", answer: "2" },
      { question: "Ildiz turlaridan eng asosiysi nima deyiladi?", answer: "asosiy ildiz" },
      { question: "Guldagi otalik va onalik birlashishi jarayoni?", answer: "urug'lanish" },
      { question: "Chang donachalarining urug'chiga kelib tushishi?", answer: "changlanish" },
      { question: "Organizmlarning o'z belgi-xususiyatlarini avlodga berishi?", answer: "irsiyat" },
      { question: "Organizmlarning hayot davomida o'zgarish xususiyati?", answer: "o'zgaruvchanlik" },
      { question: "Tabiat va tirik organizmlar aloqasini o'rganuvchi fan?", answer: "ekologiya" },
      { question: "Bakteriyalarni zararlovchi viruslar nima deyiladi?", answer: "bakteriofag" }
    ],
    kimyo: [
      { question: "Suvning kimyoviy formulasi?", answer: "H2O" },
      { question: "Karbonat angidrid gazi formulasi?", answer: "CO2" },
      { question: "Osh tuzining kimyoviy formulasi?", answer: "NaCl" },
      { question: "Kislorod gazining formulasi?", answer: "O2" },
      { question: "Ozon gazining kimyoviy formulasi?", answer: "O3" },
      { question: "Mendeleyev jadvalidagi birinchi element?", answer: "vodorod" },
      { question: "Mendeleyev jadvalida Fe qaysi element?", answer: "temir" },
      { question: "Mendeleyev jadvalida Au qaysi metall?", answer: "oltin" },
      { question: "Mendeleyev jadvalida Ag qaysi metall?", answer: "kumush" },
      { question: "Mendeleyev jadvalida Cu qaysi metall?", answer: "mis" },
      { question: "Eng yengil element (gaz)?", answer: "vodorod" },
      { question: "Oddiy sharoitda yagona suyuq metall?", answer: "simob" },
      { question: "Neytral eritmalarda pH qiymati nechaga teng?", answer: "7" },
      { question: "Sulfat kislotaning formulasi?", answer: "H2SO4" },
      { question: "Tuz kislotasining formulasi?", answer: "HCl" },
      { question: "Nitrat kislotaning formulasi?", answer: "HNO3" },
      { question: "Ammiak gazining kimyoviy formulasi?", answer: "NH3" },
      { question: "Metan gazining kimyoviy formulasi?", answer: "CH4" },
      { question: "Is gazining kimyoviy formulasi?", answer: "CO" },
      { question: "Eng aktiv nemetall element?", answer: "ftor" },
      { question: "Havoning taxminan 78 foizini tashkil etuvchi gaz?", answer: "azot" },
      { question: "Marmar va ohaktoshning asosiy formulasi?", answer: "CaCO3" },
      { question: "Vodorod peroksidning formulasi?", answer: "H2O2" },
      { question: "Organik kimyo asosan qaysi element birikmalarini o'rganadi?", answer: "uglerod" },
      { question: "Olmos va grafit qaysi elementning shakllari?", answer: "uglerod" },
      { question: "Kimyoviy reaksiya tezligini oshiradigan moddalar?", answer: "katalizator" },
      { question: "Kimyoviy reaksiya tezligini kamaytiradigan moddalar?", answer: "ingibitor" },
      { question: "Oddiy sharoitda suyuq holatdagi yagona nemetall?", answer: "brom" },
      { question: "Faqat bir xil turdagi atomlardan tashkil topgan moddalar?", answer: "oddiy moddalar" },
      { question: "Har xil turdagi atomlardan tashkil topgan moddalar?", answer: "murakkab moddalar" },
      { question: "Atomning musbat zaryadlangan zarrachasi?", answer: "proton" },
      { question: "Atomning manfiy zaryadlangan zarrachasi?", answer: "elektron" },
      { question: "Atomning zaryadsiz zarrachasi nima?", answer: "neytron" },
      { question: "Elementlarning vodorod atomini biriktira olish xossasi?", answer: "valentlik" },
      { question: "Modda miqdori o'lchov birligi nima?", answer: "mol" },
      { question: "Gidroksoniy ionining kimyoviy ifodasi?", answer: "H3O+" },
      { question: "Eritma muhitini aniqlashda ishlatiladigan qog'ozlar?", answer: "indikator" },
      { question: "Kislotali muhitda lakmus qog'ozi qaysi rangga kiradi?", answer: "qizil" },
      { question: "Ishqoriy muhitda fenolftalein qaysi rangga kiradi?", answer: "to'q qizil" },
      { question: "Oksidlanish darajasining ortishi jarayoni?", answer: "oksidlanish" },
      { question: "Oksidlanish darajasining kamayishi jarayoni?", answer: "qaytarilish" },
      { question: "Eng kuchli kislotalardan biri, sulfat yoki sirka?", answer: "sulfat" },
      { question: "Glyukozaning kimyoviy formulasi?", answer: "C6H12O6" },
      { question: "Etil spirtining kimyoviy formulasi?", answer: "C2H5OH" },
      { question: "Atsetilen gazining formulasi?", answer: "C2H2" },
      { question: "Bir xil molekulyar formulaga, lekin har xil tuzilishga ega moddalar?", answer: "izomerlar" },
      { question: "Davriy sistemada vertikal qatorlar nima deyiladi?", answer: "guruh" },
      { question: "Davriy sistemada gorizontal qatorlar nima deyiladi?", answer: "davr" },
      { question: "Suvda eriganda ionlarga ajraladigan moddalar?", answer: "elektrolitlar" },
      { question: "Tuzlarning suv ta'sirida parchalanish jarayoni?", answer: "gidroliz" }
    ],
    tarix: [
      { question: "Amir Temur qaysi yili tug'ilgan?", answer: "1336" },
      { question: "O'zbekiston mustaqillikka erishgan yil?", answer: "1991" },
      { question: "Ikkinchi jahon urushi qaysi yili tugagan?", answer: "1945" },
      { question: "Amir Temur saltanati poytaxti qaysi shahar bo'lgan?", answer: "Samarqand" },
      { question: "Zardushtiylikning muqaddas kitobi?", answer: "Avesto" },
      { question: "Qadimgi Misr hukmdorlari qanday nomlangan?", answer: "fir'avn" },
      { question: "Amerika qit'asini kashf etgan dengizchi?", answer: "Kolumb" },
      { question: "Hindistonda Boburiylar sulolasiga asos solgan bobomiz?", answer: "Bobur" },
      { question: "Birinchi jahon urushi boshlangan yil?", answer: "1914" },
      { question: "O'zbekiston Respublikasi Konstitutsiyasi qabul qilingan oy?", answer: "dekabr" },
      { question: "Amir Temurning buyuk nabirasi, olim va hukmdor kim?", answer: "Ulug'bek" },
      { question: "Al-Xorazmiy Bag'doddagi qaysi ilm markaziga rahbar bo'lgan?", answer: "Baytul hikma" },
      { question: "Teshiktosh g'ori O'zbekistonning qaysi viloyatida?", answer: "Surxondaryo" },
      { question: "Eron shohi Kir II ni mag'lub etgan mard sak malikasi?", answer: "To'maris" },
      { question: "Doro I qo'shinini chalg'itgan mard cho'pon bobomiz?", answer: "Shiroq" },
      { question: "Makedoniyalik Aleksandrga qarshi kurashgan so'g'd qahramoni?", answer: "Spitamen" },
      { question: "Chingizxon qo'shinlariga qarshi mardona kurashgan xorazmlik sarkarda?", answer: "Jaloliddin" },
      { question: "Qadimgi Rimda eng yirik qullar qo'zg'oloni rahbari?", answer: "Spartak" },
      { question: "G'arbiy Rim imperiyasi qaysi yili qulagan?", answer: "476" },
      { question: "Fransiyaning imperatori bo'lgan mashhur sarkarda?", answer: "Napoleon" },
      { question: "Qadimgi dunyoning eng birinchi yozma qonunlar muallifi (Bobil shohi)?", answer: "Xammurapi" },
      { question: "Amir Temur va Boyazid o'rtasidagi mashhur jang?", answer: "Anqara jangi" },
      { question: "Anqara jangi qaysi yili bo'lib o'tgan?", answer: "1402" },
      { question: "Turkiston Muxtoriyati tashkil topgan yil?", answer: "1917" },
      { question: "Birlashgan Millatlar Tashkiloti (BMT) tuzilgan yil?", answer: "1945" },
      { question: "IX-X asrlarda Movarounnahrda hukm surgan o'zbek sulolasi?", answer: "Somoniylar" },
      { question: "Buxoro amirligining eng so'nggi amiri kim?", answer: "Olimxon" },
      { question: "Rossiya imperiyasi Toshkentni bosib olgan yil?", answer: "1865" },
      { question: "XIX asrda o'zbek zaminida nechta xonlik (amirlik) bor edi?", answer: "3" },
      { question: "Turkistonda ma'rifatparvarlik va yangi usul maktablari harakati?", answer: "jadidchilik" },
      { question: "Jadidlar yetakchisi, 'Padarkush' dramasi muallifi?", answer: "Behbudiy" },
      { question: "Qadimgi Yunonistonda sport o'yinlari vatani?", answer: "Olimpiya" },
      { question: "Buyuk fransuz burjua inqilobi boshlangan yil?", answer: "1789" },
      { question: "Ikkinchi jahon urushi boshlangan yil?", answer: "1939" },
      { question: "Birinchi jahon urushi tugagan yil?", answer: "1918" },
      { question: "Dunyo tarixida ilk bor qog'oz qaysi davlatda kashf etilgan?", answer: "Xitoy" },
      { question: "Qadimgi dunyoda demokratiya vatani hisoblangan shahar?", answer: "Afina" },
      { question: "Arab xalifaligiga qarshi Movarounnahrdagi qo'zg'olon rahbari (Muqanna)?", answer: "Muqanna" },
      { question: "Temuriylar davrida Hirotda yashab ijod qilgan o'zbek she'riyati sultoni?", answer: "Navoiy" },
      { question: "Mirzo Ulug'bek rasadxonasi qaysi shaharda joylashgan?", answer: "Samarqand" },
      { question: "Amir Temur qaysi davlatga yurish vaqtida vafot etgan?", answer: "Xitoy" },
      { question: "Shohrux Mirzo saltanat poytaxtini qaysi shaharga ko'chirgan edi?", answer: "Hirot" },
      { question: "Qadimgi Dunyo etti mo'jizasidan biri bo'lgan ehromlar yurti?", answer: "Misr" },
      { question: "Nil daryosi bo'yida joylashgan qadimgi buyuk davlat?", answer: "Misr" },
      { question: "O'zbekiston Respublikasi bayrog'i qabul qilingan yil?", answer: "1991" },
      { question: "O'zbekiston Respublikasi milliy valyutasi (so'm) qaysi yili muomalaga kiritildi?", answer: "1994" },
      { question: "G'arbda 'Avitsenna' nomi bilan mashhur bo'lgan alloma bobomiz?", answer: "Ibn Sino" },
      { question: "Tarix fanining otasi deb tan olingan qadimgi yunon olimi?", answer: "Gerodot" },
      { question: "Qadimgi Rim hukmdori bo'lgan, 'Keldim, ko'rdim, g'alaba qozondim' iborasi muallifi?", answer: "Sezar" },
      { question: "Jaloliddin Manguberdi qaysi daryodan sakrab o'tib, Chingizxonni hayratda qoldirgan?", answer: "Sind" }
    ],
    ingliztili: [
      { question: "What is the past form of 'Go'?", answer: "went" },
      { question: "What is the past participle (V3) of 'Eat'?", answer: "eaten" },
      { question: "What is the plural of 'Child'?", answer: "children" },
      { question: "What is the plural of 'Man'?", answer: "men" },
      { question: "What is the plural of 'Mouse'?", answer: "mice" },
      { question: "What is the opposite of 'Big'?", answer: "small" },
      { question: "What is the opposite of 'Good'?", answer: "bad" },
      { question: "What is the opposite of 'Hot'?", answer: "cold" },
      { question: "What is the opposite of 'Day'?", answer: "night" },
      { question: "What is the opposite of 'Black'?", answer: "white" },
      { question: "What color do you get by mixing red and white?", answer: "pink" },
      { question: "How many letters are there in the English alphabet?", answer: "26" },
      { question: "Which month comes after May?", answer: "june" },
      { question: "Which day comes after Friday?", answer: "saturday" },
      { question: "What is a baby dog called?", answer: "puppy" },
      { question: "What is a baby cat called?", answer: "kitten" },
      { question: "The capital city of the UK?", answer: "london" },
      { question: "The capital city of the USA?", answer: "washington" },
      { question: "Comparative form of the adjective 'Bad'?", answer: "worse" },
      { question: "Superlative form of the adjective 'Good'?", answer: "best" },
      { question: "Past simple of the verb 'Do'?", answer: "did" },
      { question: "Past simple of the verb 'Have'?", answer: "had" },
      { question: "Past simple of the verb 'See'?", answer: "saw" },
      { question: "Past simple of the verb 'Take'?", answer: "took" },
      { question: "What is the opposite of the word 'First'?", answer: "last" },
      { question: "Which preposition goes with 'interested'?", answer: "in" },
      { question: "Which preposition goes with 'afraid'?", answer: "of" },
      { question: "Which preposition goes with 'depend'?", answer: "on" },
      { question: "What is the synonym of 'Quick'?", answer: "fast" },
      { question: "What is the synonym of 'Beautiful'?", answer: "pretty" },
      { question: "What is the plural of 'Tooth'?", answer: "teeth" },
      { question: "What is the plural of 'Foot'?", answer: "feet" },
      { question: "The antonym of 'Rich'?", answer: "poor" },
      { question: "The antonym of 'Happy'?", answer: "sad" },
      { question: "The antonym of 'Easy'?", answer: "difficult" },
      { question: "What do you call a person who flies a plane?", answer: "pilot" },
      { question: "What do you call a person who cooks in a restaurant?", answer: "chef" },
      { question: "What is the English word for 'Kitob'?", answer: "book" },
      { question: "What is the English word for 'Maktab'?", answer: "school" },
      { question: "What is the English word for 'Oila'?", answer: "family" },
      { question: "What is the negative short form of 'will not'?", answer: "won't" },
      { question: "What suffix is added to 'quick' to make it an adverb?", answer: "ly" },
      { question: "What currency is used in the UK?", answer: "pound" },
      { question: "What currency is used in the USA?", answer: "dollar" },
      { question: "How many days are there in a week?", answer: "7" },
      { question: "How many months are there in a year?", answer: "12" },
      { question: "What is the opposite of 'Buy'?", answer: "sell" },
      { question: "What is the opposite of 'Love'?", answer: "hate" },
      { question: "Translate into English: 'Olma'", answer: "apple" }
    ],
    geografiya: [
      { question: "O'zbekiston Respublikasining poytaxti?", answer: "Toshkent" },
      { question: "Eng katta materik (quruqlik)?", answer: "Evroosiyo" },
      { question: "Eng kichik materik?", answer: "Avstraliya" },
      { question: "Eng katta okean?", answer: "Tinch" },
      { question: "Eng kichik okean?", answer: "Shimoliy muz" },
      { question: "Dunyodagi eng baland cho'qqi (tog')?", answer: "Everest" },
      { question: "Dunyodagi eng uzun daryo?", answer: "Nil" },
      { question: "Dunyodagi eng chuqur ko'l?", answer: "Baykal" },
      { question: "Dunyodagi eng katta issiq sahro (cho'l)?", answer: "Sahroi Kabir" },
      { question: "O'zbekiston hududining katta qismini egallagan cho'l?", answer: "Qizilqum" },
      { question: "Yer sharining kichraytirilgan modeli?", answer: "globus" },
      { question: "Dunyodagi eng katta orol?", answer: "Grenlandiya" },
      { question: "Yaponiya davlatining poytaxti?", answer: "Tokio" },
      { question: "Fransiya davlatining poytaxti?", answer: "Parij" },
      { question: "Rossiya davlatining poytaxti?", answer: "Moskva" },
      { question: "Turkiya davlatining poytaxti?", answer: "Anqara" },
      { question: "AQSh davlatining poytaxti?", answer: "Vashington" },
      { question: "Buyuk Britaniyaning poytaxti?", answer: "London" },
      { question: "Xitoy davlatining poytaxti?", answer: "Pekin" },
      { question: "Maydoni bo'yicha dunyodagi eng katta davlat?", answer: "Rossiya" },
      { question: "Dunyodagi eng baland sharshara?", answer: "Anxel" },
      { question: "O'zbekistonning eng janubiy viloyati?", answer: "Surxondaryo" },
      { question: "O'zbekiston maydoni taxminan necha ming kvadrat kilometr?", answer: "448.9" },
      { question: "Kompasning shimolni ko'rsatadigan mili qaysi rangda bo'ladi?", answer: "ko'k" },
      { question: "Dunyoning nolinchi meridiani o'tadigan joy (shahar)?", answer: "Grinvich" },
      { question: "Yer sharining markazini ikki teng qismga bo'luvchi chiziq?", answer: "ekvator" },
      { question: "Ekvator chizig'ining uzunligi necha ming kilometr?", answer: "40" },
      { question: "Yerning havo qobig'i nima deyiladi?", answer: "atmosfera" },
      { question: "Yerning tosh (qattiq) qobig'i nima deyiladi?", answer: "litosfera" },
      { question: "Yerning suv qobig'i nima deyiladi?", answer: "gidrosfera" },
      { question: "Yerning hayot (tiriklik) qobig'i nima deyiladi?", answer: "biosfera" },
      { question: "Atmosferaning eng quyi, ob-havo shakllanadigan qatlami?", answer: "troposfera" },
      { question: "Dunyodagi eng sersuv va eng yirik havzali daryo?", answer: "Amazonka" },
      { question: "Eng katta yarim orol qaysi?", answer: "Arabiston" },
      { question: "O'zbekiston bilan chegaradosh eng uzun davlat?", answer: "Qozog'iston" },
      { question: "O'zbekiston janubda qaysi davlat bilan chegaradosh?", answer: "Afg'oniston" },
      { question: "Vulkan cho'qqisidagi voronkasimon chuqurlik?", answer: "krater" },
      { question: "Yer o'z o'qi atrofida qaysi tomondan qaysi tomonga aylanadi?", answer: "g'arbdan sharqqa" },
      { question: "Janubiy qutbda joylashgan muzlagan materik?", answer: "Antarktida" },
      { question: "Italiya davlatining poytaxti?", answer: "Rim" },
      { question: "Misr davlatining poytaxti?", answer: "Qohira" },
      { question: "Hindiston davlatining poytaxti?", answer: "Nyu-Dehli" },
      { question: "Ispaniya davlatining poytaxti?", answer: "Madrid" },
      { question: "Kanada davlatining poytaxti?", answer: "Ottava" },
      { question: "Avstraliya ittifoqining poytaxti qaysi shahar?", answer: "Kanberra" },
      { question: "Okean tubidagi zilzilalar natijasida hosil bo'ladigan ulkan to'lqin?", answer: "tsunami" },
      { question: "Yer po'stining ostidagi qaynoq, suyuq magma qatlami joylashgan joy?", answer: "mantiya" },
      { question: "Yer sharining eng markaziy, eng issiq qismi?", answer: "yadro" },
      { question: "Atmosferadagi ultrabinafsha nurlarni to'suvchi gaz qatlami?", answer: "ozon" },
      { question: "O'zbekistonning maydoni bo'yicha eng katta viloyati (hududi)?", answer: "Navoiy" }
    ]

  }

  };
