/**
 * Ziyomap Games — QO'SHIMCHA SAVOLLAR (2-fayl)
 * Yangi savollar qo'shish uchun shu faylni tahrirlang.
 * questions-loader.js avtomatik birlashtiradi.
 */

const QUIZ_QUESTIONS_2 = {
  fizika: [
    { q: "Yorug'likning to'lqin uzunligi va chastota bog'lanishi?",
      a: 1, o: ["λ = f/c","λ = c/f","λ = c·f","λ = f²/c"],
      e: "λ = c/f — to'lqin tezligi = chastota × uzunlik.", d: "medium" },
    { q: "Ideal gaz molekulalarining o'zaro ta'siri?",
      a: 2, o: ["Kuchli","O'rtacha","Yo'q","Faqat tortishish"],
      e: "Ideal gazda molekulalar o'rtasida o'zaro ta'sir yo'q deb olinadi.", d: "hard" },
    { q: "Magnit maydon chiziqlari qayerdan chiqadi?",
      a: 0, o: ["Shimol qutbidan","Janub qutbidan","Markazdan","Atrofdan"],
      e: "Magnit maydon chiziqlari shimol qutbidan chiqib janubga kiradi.", d: "easy" },
    { q: "Yorug'lik manbadan uzoqlashganda chastota qanday o'zgaradi?",
      a: 1, o: ["Ortadi","Kamayadi","O'zgarmaydi","Avval ortib keyin kamayadi"],
      e: "Doppler effektiga ko'ra manba uzoqlashganda chastota kamayadi (qizilga siljish).", d: "hard" },
    { q: "Rentgen nurlarini kim kashf etdi?",
      a: 2, o: ["Kyuri","Rezerford","Rentgen","Tomson"],
      e: "Vilgelm Rentgen 1895-yilda rentgen nurlarini kashf etgan.", d: "medium" },
    { q: "Yadro reaksiyasida qanday qonun saqlanadi?",
      a: 0, o: ["Massa va energiya saqlanishi","Impuls saqlanishi","Zaryad saqlanishi","Barchasi"],
      e: "Yadro reaksiyasida massa va energiya, impuls, zaryad saqlanadi.", d: "hard" },
    { q: "Elektr tokining issiqlik ta'siri formulasi?",
      a: 2, o: ["Q = I·U","Q = I²·R","Q = I²·R·t","Q = U·t"],
      e: "Joule-Lens qonuni: Q = I²·R·t.", d: "medium" },
    { q: "Yer sirtidan qochish tezligi (2-kosmik tezlik)?",
      a: 1, o: ["7.9 km/s","11.2 km/s","16.7 km/s","5.0 km/s"],
      e: "2-kosmik tezlik ≈ 11.2 km/s — Yer tortishishidan chiqish tezligi.", d: "hard" },
    { q: "Tebranish konturidagi rezonans nima?",
      a: 1, o: ["Chastota keskin kamayadi","Amplituda keskin ortadi","Tok to'xtaydi","Kondensator zaryadsizlanadi"],
      e: "Rezonans — xususiy va tashqi chastota mos kelganda amplituda keskin ortadi.", d: "medium" },
    { q: "Elektr maydon kuchlanganlik birligi?",
      a: 2, o: ["Volt","Nyuton","V/m","Joul"],
      e: "Elektr maydon kuchlanganligi E = V/m (Volt/metr).", d: "medium" },
    { q: "Ovoz to'lqini qaysi muhitda eng tez tarqaladi?",
      a: 3, o: ["Vakuum","Gaz","Suyuqlik","Qattiq jism"],
      e: "Ovoz qattiq jismlarda eng tez tarqaladi (chunki zarralar yaqin).", d: "easy" },
    { q: "Kondensator sig'imi birligi?",
      a: 1, o: ["Genri","Farad","Om","Veber"],
      e: "Kondensator sig'imi — Farad (F).", d: "medium" },
    { q: "Yadro parchalanish reaksiyasida neytronlar soni?",
      a: 0, o: ["Ko'payadi","Kamayadi","O'zgarmaydi","Nolga teng"],
      e: "Yadro parchalanishida neytronlar soni ortadi — zanjir reaksiyasi.", d: "hard" },
    { q: "Birinchi kosmik tezlik (Yer uchun)?",
      a: 0, o: ["7.9 km/s","9.8 km/s","11.2 km/s","3.0 km/s"],
      e: "Birinchi kosmik tezlik ≈ 7.9 km/s — sun'iy yo'ldosh tezligi.", d: "hard" },
    { q: "O'tkazgichlarni parallel ulashda umumiy qarshilik?",
      a: 2, o: ["R₁+R₂","R₁·R₂","1/R₁+1/R₂ nisbat","R₁−R₂"],
      e: "Parallel ulashda: 1/R = 1/R₁ + 1/R₂ + ...", d: "medium" },
    { q: "Magnit maydonining manbai nima?",
      a: 0, o: ["Harakatdagi elektr zaryadlar","Tinch turgan zaryadlar","Faqat magnitlar","Faqat o'tkazgichlar"],
      e: "Magnit maydoni harakatdagi elektr zaryadlar (tok) tomonidan hosil qilinadi.", d: "medium" },
    { q: "Suyuqlikning bug'lanishida nima sodir bo'ladi?",
      a: 1, o: ["Temperatura ortadi","Suyuqlik soviydi","Bosim ortadi","Hajm kamayadi"],
      e: "Bug'lanishda suyuqlik soviydi, chunki eng tez molekulalar uchib chiqadi.", d: "easy" },
    { q: "Mikroskopda qanday linzalar ishlatiladi?",
      a: 0, o: ["Yig'uvchi linzalar","Sochuvchi linzalar","Yassi oyna","Pri zm a"],
      e: "Mikroskopda ikkala linza ham yig'uvchi (obyektiv va okulyar).", d: "medium" },
    { q: "O'zgarmas tok generatori nima?",
      a: 1, o: ["Kondensator","Dinamo (kollektorli)","Transformator","Rektifikator"],
      e: "O'zgarmas tok generatori — dinamo, kollektor yordamida o'zgarmas tok hosil qiladi.", d: "hard" },
    { q: "Energiyaning saqlanish qonuniga ko'ra energiya?",
      a: 2, o: ["Yo'qoladi","Yaratiladi","Bir turdan ikkinchisiga o'tadi","Faqat issiqlikka aylanadi"],
      e: "Energiya hech qayerdan yo'qolmaydi — faqat bir shakldan boshqasiga o'tadi.", d: "easy" },
  ],
  matematika: [
    { q: "2³ × 2² = ?",
      a: 1, o: ["2⁵","2⁶","4⁵","2⁹"],
      e: "2³ × 2² = 2⁵ = 32.", d: "easy" },
    { q: "√144 = ?",
      a: 2, o: ["11","13","12","14"],
      e: "12 × 12 = 144.", d: "easy" },
    { q: "Lim (x→0) sin(x)/x = ?",
      a: 0, o: ["1","0","∞","π"],
      e: "Bu klassik limit = 1.", d: "hard" },
    { q: "To'rtburchakning yuzasi formulasi?",
      a: 2, o: ["a + b","2(a + b)","a · b","a / b"],
      e: "To'rtburchak yuzasi S = a · b (eni × bo'yi).", d: "easy" },
    { q: "Agar son 15% ga oshsa, uni qanday koeffitsientga ko'paytiriladi?",
      a: 1, o: ["0.15","1.15","1.5","0.85"],
      e: "15% oshish = 100% + 15% = 115% = 1.15 koeffitsient.", d: "easy" },
    { q: "Ildizlar yig'indisi (kvadrat tenglama x² - 5x + 6 = 0)?",
      a: 0, o: ["5","6","-5","-6"],
      e: "Viyet teoremasi: x₁+x₂ = 5, x₁·x₂ = 6.", d: "medium" },
    { q: "Kubning hajmi formulasi?",
      a: 1, o: ["6a²","a³","a²","4a²"],
      e: "Kub hajmi V = a³ (a — qirra uzunligi).", d: "easy" },
    { q: "12 va 18 ning eng kichik umumiy karralisi (EKUK)?",
      a: 2, o: ["24","18","36","48"],
      e: "EKUK(12,18) = 36 (12×3, 18×2).", d: "medium" },
    { q: "45° burchakning radian o'lchovi?",
      a: 1, o: ["π/2","π/4","π/3","π/6"],
      e: "45° = π/4 radian.", d: "easy" },
    { q: "Koordinatalar tekisligida (0;7) nuqta qayerda joylashgan?",
      a: 2, o: ["Ox o'qida","Boshlang'ich nuqta","Oy o'qida","III chorakda"],
      e: "(0;7) nuqta Oy o'qida (x=0, y=7).", d: "easy" },
    { q: "Funksiyaning hosilasi nima ifodalaydi?",
      a: 1, o: ["Yuzani","O'zgarish tezligini","Hajmni","Tenglamani"],
      e: "Hosila — funksiyaning o'zgarish tezligi (bir nuqtadagi oniy tezlik).", d: "medium" },
    { q: "1000 ning 20% i necha?",
      a: 0, o: ["200","20","500","100"],
      e: "1000 × 20/100 = 200.", d: "easy" },
    { q: "Quyidagi sonlardan qaysi biri murakkab son?",
      a: 2, o: ["2","3","9","7"],
      e: "9 murakkab son (3×3), qolganlari tub.", d: "easy" },
    { q: "Sferaning yuzasi formulasi?",
      a: 1, o: ["4πr²","4πr³/3","πr²","2πr²"],
      e: "Sfera yuzasi S = 4πr².", d: "medium" },
    { q: "Agar kvadrat tenglama D=0 bo'lsa, nechta ildiz bor?",
      a: 0, o: ["Bitta (ikkala teng)","Ikkita har xil","Ildiz yo'q","Cheksiz"],
      e: "D=0 → bitta ildiz (ikkala ildiz teng).", d: "medium" },
    { q: "y = kx + b to'g'ri chiziqda k nima?",
      a: 1, o: ["Erkin had","Burchak koeffitsienti","Kesma uzunligi","Nishab burchagi"],
      e: "k — burchak koeffitsienti (qiyalik).", d: "easy" },
    { q: "Vektorlarning vektor ko'paytmasi natijasi?",
      a: 2, o: ["Skalyar miqdor","Vektor","Vektor (perpendikulyar)","Nol"],
      e: "Ikki vektorning vektor ko'paytmasi ikkalasiga perpendikulyar vektor.", d: "hard" },
    { q: "Modul tenglama |x| = 5 → x = ?",
      a: 1, o: ["Faqat 5","5 yoki -5","Faqat -5","25"],
      e: "|x| = 5 → x = 5 yoki x = -5.", d: "easy" },
    { q: "Trigonometrik ayniyat: 1 + tg²θ = ?",
      a: 2, o: ["sin²θ","cos²θ","1/cos²θ","ctg²θ"],
      e: "1 + tg²θ = 1/cos²θ (seans²θ).", d: "hard" },
    { q: "a·(b + c) = a·b + a·c qaysi qonun?",
      a: 0, o: ["Taqsimot qonuni","O'rin almashtirish","Guruhlash","Assotsiativlik"],
      e: "Bu taqsimot (distributive) qonuni.", d: "easy" },
  ],
  informatika: [
    { q: "IPv4 manzil necha bit?",
      a: 2, o: ["16","64","32","128"],
      e: "IPv4 — 32 bit (4 oktet).", d: "medium" },
    { q: "Stack ma'lumotlar tuzilmasi printsipi?",
      a: 0, o: ["LIFO","FIFO","LILO","Random"],
      e: "Stack — Last In, First Out.", d: "medium" },
    { q: "Qaysi tarmoq topologiyasida barcha qurilmalar bir kabelga ulangan?",
      a: 1, o: ["Yulduz","Shina","Halqa","Mesh"],
      e: "Shina (bus) topologiyasida barcha qurilmalar bitta asosiy kabelga ulanadi.", d: "medium" },
    { q: "Python'da 'len()' funksiyasi nima qaytaradi?",
      a: 0, o: ["Elementlar soni","Oxirgi element","Birinchi element","Yig'indi"],
      e: "len() — obyekt uzunligi/elementlar sonini qaytaradi.", d: "easy" },
    { q: "SQL'da jadval yaratish buyrug'i?",
      a: 1, o: ["INSERT","CREATE TABLE","ALTER TABLE","SELECT"],
      e: "CREATE TABLE — yangi jadval yaratadi.", d: "medium" },
    { q: "Veb-saytlar qaysi portda ishlaydi (HTTP)?",
      a: 2, o: ["21","25","80","443"],
      e: "HTTP port 80, HTTPS port 443.", d: "easy" },
    { q: "Agile usulida sprint davomiyligi odatda?",
      a: 1, o: ["1 hafta","2-4 hafta","6 oy","1 yil"],
      e: "Sprint odatda 2-4 hafta davom etadi.", d: "medium" },
    { q: "PHP'da o'zgaruvchi qanday boshlanadi?",
      a: 0, o: ["$","#","@","&"],
      e: "PHP o'zgaruvchilari $ bilan boshlanadi.", d: "easy" },
    { q: "JSON formati nima uchun ishlatiladi?",
      a: 0, o: ["Ma'lumot almashish","Rasm saqlash","Video oqim","Dizayn yaratish"],
      e: "JSON ma'lumotlarni tuzilgan formatda almashish uchun ishlatiladi.", d: "easy" },
    { q: "C++ dasturlash tilida 'cin >>' nima uchun?",
      a: 1, o: ["Chop etish","Kiritish","Qaytarish","O'chirish"],
      e: "cin >> — foydalanuvchidan ma'lumot kiritish uchun.", d: "medium" },
    { q: "Ma'lumotlar bazasidagi 'Primary Key' nima?",
      a: 2, o: ["Takrorlanuvchi qiymat","Bo'sh qiymat","Unikal identifikator","Chegara"],
      e: "Primary Key — har bir qatorni unikal identifikatsiya qiluvchi maydon.", d: "medium" },
    { q: "Git'da branch yaratish buyrug'i?",
      a: 0, o: ["git branch <nomi>","git new <nomi>","git create <nomi>","git add <nomi>"],
      e: "git branch <branch_nomi> — yangi branch yaratadi.", d: "medium" },
    { q: "XSS hujumi nima?",
      a: 0, o: ["Saytlararo skript hujumi","Virus tarqatish","Parol o'g'irlash","Serverni buzish"],
      e: "XSS (Cross-Site Scripting) — zararli skriptni sahifaga joylashtirish.", d: "hard" },
    { q: "Quyidagilardan qaysi biri Python kalit so'zi emas?",
      a: 2, o: ["if","else","function","while"],
      e: "Python def ishlatadi, function emas.", d: "easy" },
    { q: "HTTP 301 kodi nimani anglatadi?",
      a: 1, o: ["Yangi kontent","Doimiy yo'naltirish","Vaqtincha yo'naltirish","Server xatosi"],
      e: "301 — doimiy yo'naltirish (redirect).", d: "medium" },
    { q: "Virtual xotira nima?",
      a: 1, o: ["RAM dan foydalanish","Diskni xotira sifatida ishlatish","CPU kesh","Tashqi disk"],
      e: "Virtual xotira operativ xotiraning kengaytmasi sifatida diskdan foydalanadi.", d: "hard" },
    { q: "NoSQL ma'lumotlar bazasiga misol?",
      a: 0, o: ["MongoDB","MySQL","PostgreSQL","SQLite"],
      e: "MongoDB NoSQL (hujjatli) ma'lumotlar bazasi.", d: "medium" },
    { q: "Sortlash algoritmlaridan eng tezi (o'rtacha)?",
      a: 1, o: ["Bubble sort","Quick sort","Selection sort","Insertion sort"],
      e: "Quick sort — o'rtacha O(n log n) va juda tez.", d: "medium" },
    { q: "Qaysi operatsion tizim ochiq kodli?",
      a: 2, o: ["Windows","macOS","Linux","iOS"],
      e: "Linux — ochiq kodli (open source) operatsion tizim.", d: "easy" },
    { q: "API'da GET va POST asosiy farqi?",
      a: 0, o: ["GET — olish, POST — yuborish","GET — tezroq","POST — faqat rasm","Farqi yo'q"],
      e: "GET ma'lumot olish uchun, POST yangi ma'lumot yuborish/yaratish uchun.", d: "medium" },
  ],
  biologiya: [
    { q: "Fotosintezda qaysi gaz chiqadi?",
      a: 1, o: ["CO₂","O₂","N₂","H₂"],
      e: "Fotosintez mahsuloti — kislorod (O₂).", d: "easy" },
    { q: "Inson qonidagi gemoglobin vazifasi?",
      a: 0, o: ["Kislorod tashish","Ovqat hazm qilish","Immunitet","Qon ivish"],
      e: "Gemoglobin kislorodni o'pkadan organizmga yetkazadi.", d: "easy" },
    { q: "Inson organizmida eng ko'p uchraydigan element?",
      a: 1, o: ["Uglerod","Kislorod","Vodorod","Azot"],
      e: "Inson tanasining ~65% ini kislorod tashkil qiladi (suv tarkibida).", d: "medium" },
    { q: "Qon quyishda eng muhim omil?",
      a: 2, o: ["Yosh","Vazn","Qon guruhi mosligi","Jins"],
      e: "Qon quyishda donor va retsipient qon guruhlari mos bo'lishi kerak.", d: "easy" },
    { q: "Oqsil monomeri nima?",
      a: 0, o: ["Aminokislota","Nukleotid","Monosaxarid","Glitserin"],
      e: "Oqsillar monomerlari — aminokislotalar.", d: "medium" },
    { q: "O'simliklarda suv va mineral moddalar qaysi to'qima orqali ko'tariladi?",
      a: 1, o: ["Floema","Ksilema","Kambiy","Epidermis"],
      e: "Ksilema suv va mineral moddalarni ildizdan barglarga ko'taradi.", d: "medium" },
    { q: "Odam miyasining eng katta qismi?",
      a: 0, o: ["Katta miya (serebrum)","Miyacha","Uzunchoq miya","O'rta miya"],
      e: "Katta miya (serebrum) — miyaning eng katta qismi, ~85%.", d: "easy" },
    { q: "Ovqat hazm qilishning birinchi bosqichi?",
      a: 1, o: ["Me'da","Og'iz bo'shlig'i","Ingichka ichak","Yo'g'on ichak"],
      e: "Ovqat hazmi og'iz bo'shlig'ida boshlanadi (tishlar, tuprik).", d: "easy" },
    { q: "Ayollarda necha juft xromosoma?",
      a: 0, o: ["23 juft","22 juft","24 juft","46 juft"],
      e: "Odamda 23 juft (46 ta) xromosoma: 22 autosoma + 1 jinsiy.", d: "medium" },
    { q: "Eritrositlarning asosiy vazifasi?",
      a: 2, o: ["Immunitet","Qon ivish","Kislorod tashish","Gormon ishlab chiqarish"],
      e: "Eritrositlar (qizil qon hujayralari) gemoglobin orqali O₂ va CO₂ tashiydi.", d: "easy" },
    { q: "Bakteriyalarning hujayra devori nima?",
      a: 1, o: ["Sellyuloza","Peptidoglikan","Xitin","Lipid"],
      e: "Bakteriya hujayra devori peptidoglikandan iborat (murein).", d: "hard" },
    { q: "Katalizator sifatida ishlovchi oqsil?",
      a: 0, o: ["Ferment (enzim)","Gormon","Antitelo","Vitamin"],
      e: "Fermentlar — biologik katalizatorlar, oqsil tabiatli.", d: "medium" },
    { q: "Gipofiz qayerda joylashgan?",
      a: 2, o: ["Bo'yinda","Ko'krakda","Miyada","Buyrakda"],
      e: "Gipofiz miyaning asosida, 'turcica sella'da joylashgan.", d: "hard" },
    { q: "Odam necha xil sezgi a'zosiga ega?",
      a: 1, o: ["4","5","6","7"],
      e: "5 ta asosiy sezgi: ko'rish, eshitish, hid bilish, ta'm bilish, sezish.", d: "easy" },
    { q: "Meyoz bo'linish natijasida nima hosil bo'ladi?",
      a: 2, o: ["2 ta hujayra","4 ta diploid hujayra","4 ta gaploid hujayra","2 ta gaploid hujayra"],
      e: "Meyozda 4 ta gaploid (n) hujayra hosil bo'ladi (jinsiy hujayralar).", d: "medium" },
    { q: "Teri kimga tegishli?",
      a: 0, o: ["Odamning eng katta organi","Eng kichik organ","Skelet qismi","Nafas olish a'zosi"],
      e: "Teri ~2 m² yuzasi bilan odamning eng katta organi.", d: "easy" },
    { q: "Yurakning qaysi qismi kislorodli qonni haydaydi?",
      a: 0, o: ["Chap qorincha","O'ng qorincha","Chap bo'lmacha","O'ng bo'lmacha"],
      e: "Chap qorincha kislorodli qonni aortaga haydaydi.", d: "medium" },
    { q: "Insulin qaysi organda ishlab chiqariladi?",
      a: 1, o: ["Jigar","Oshqozon osti bezi","Buyrak","Me'da"],
      e: "Insulin oshqozon osti bezining Langerhans orolchalarida ishlab chiqariladi.", d: "medium" },
    { q: "Ko'zning yorug'lik sezuvchi qismi?",
      a: 0, o: ["To'r parda (retina)","Shox parda","Gavhar","Ko'z yoshi"],
      e: "Retina (to'r parda) — yorug'likni sezuvchi nerv hujayralari qatlami.", d: "medium" },
    { q: "Nafas olish markazi qayerda joylashgan?",
      a: 0, o: ["Uzunchoq miya","Katta miya","Miyacha","Orqa miya"],
      e: "Nafas olish markazi uzunchoq miyada joylashgan.", d: "hard" },
  ],
  kimyo: [
    { q: "Suvning qaynash harorati (1 atm)?",
      a: 2, o: ["0°C","50°C","100°C","200°C"],
      e: "Suv 100°C da qaynaydi (standart bosimda).", d: "easy" },
    { q: "Eng yengil element?",
      a: 0, o: ["Vodorod","Geliy","Litiy","Uglerod"],
      e: "Vodorod (H) — eng yengil element.", d: "easy" },
    { q: "Kimyoviy reaksiyada katalizator nima qiladi?",
      a: 2, o: ["Reaksiyani to'xtatadi","Issiqlik chiqaradi","Reaksiyani tezlashtiradi","Mahsulotni oshiradi"],
      e: "Katalizator reaksiyani tezlashtiradi, o'zi sarflanmaydi.", d: "easy" },
    { q: "Quyidagilardan qaysi biri oddiy modda?",
      a: 1, o: ["Suv","Kislorod (O₂)","Tuz (NaCl)","Shakar"],
      e: "Oddiy modda — bir xil atomlardan tuzilgan (O₂, H₂, Fe).", d: "easy" },
    { q: "Kimyoviy birikma CO₂ qanday nomlanadi?",
      a: 1, o: ["Uglerod oksidi","Karbonat angidrid","Uglerod kislotasi","Metan"],
      e: "CO₂ — karbonat angidrid (uglerod dioksid).", d: "easy" },
    { q: "Elektromanfiylik eng yuqori element?",
      a: 2, o: ["Kislorod","Xlor","Ftor","Azot"],
      e: "Ftor (F) — eng elektromanfiy element.", d: "hard" },
    { q: "Eritmalarda pH qiymati nima?",
      a: 0, o: ["Vodorod ionlari konsentratsiyasi","Kislorod miqdori","Harorat","Bosim"],
      e: "pH = -log[H⁺] — vodorod ionlari konsentratsiyasi.", d: "medium" },
    { q: "Oksidlanish-qaytarilish reaksiyasida qaysi jarayon sodir bo'ladi?",
      a: 0, o: ["Elektron almashinuvi","Proton almashinuvi","Neytron almashinuvi","Atom almashinuvi"],
      e: "Oksidlanish-qaytarilish — elektronlar bir atomdan ikkinchisiga o'tadi.", d: "medium" },
    { q: "Tabiiy gaz asosan nimadan iborat?",
      a: 1, o: ["Etan","Metan (CH₄)","Propan","Butan"],
      e: "Tabiiy gaz asosan metan CH₄ dan iborat.", d: "medium" },
    { q: "Qaysi element suyuq holatda (xona harorati)?",
      a: 2, o: ["Temir","Kumush","Simob (Hg)","Oltin"],
      e: "Simob (Hg) xona haroratida suyuq holatda.", d: "medium" },
    { q: "Fe + CuSO₄ → FeSO₄ + Cu reaksiya turi?",
      a: 0, o: ["O'rin olish","Birikish","Parchalanish","Almashinish"],
      e: "Fe Cu ni siqib chiqaradi — o'rin olish reaksiyasi.", d: "medium" },
    { q: "Glyukoza molekulasidagi uglerodlar soni?",
      a: 1, o: ["5","6","12","3"],
      e: "Glyukoza C₆H₁₂O₆ — 6 ta uglerod atomi.", d: "medium" },
    { q: "Laboratoriyada gaz yig'ish usuli?",
      a: 1, o: ["Filtratsiya","Suv ustida yig'ish","Distillatsiya","Kristallash"],
      e: "Gazlar suv ustida yig'iladi (agar suvda erimasa).", d: "easy" },
    { q: "Kislotaning pH qiymati?",
      a: 0, o: ["pH < 7","pH = 7","pH > 7","pH = 0"],
      e: "Kislotalar pH < 7 ga ega (qancha kichik bo'lsa, shuncha kuchli kislota).", d: "easy" },
    { q: "Molekulalararo eng kuchli bog'?",
      a: 0, o: ["Vodorod bog'","Dipol-dipol","London kuchlari","Kovalent bog'"],
      e: "Vodorod bog' — eng kuchli molekulalararo bog' (H...O, N, F).", d: "hard" },
    { q: "Kalsiy karbonat qizdirilganda nima ajraladi?",
      a: 1, o: ["Kislorod","Karbonat angidrid (CO₂)","Vodorod","Azot"],
      e: "CaCO₃ → (t°) CaO + CO₂↑", d: "medium" },
    { q: "Izotoplar — bir elementning...",
      a: 2, o: ["Turli xil kimyoviy xususiyatli","Turli elektron sonli","Turli neytron sonli","Turli proton sonli"],
      e: "Izotoplar — bir xil proton, har xil neytron sonli atomlar.", d: "medium" },
    { q: "Kimyoviy bog'ning eng kuchli turi?",
      a: 1, o: ["Vodorod bog'","Kovalent bog'","Ion bog'","Metall bog'"],
      e: "Kovalent bog' — juda kuchli, atomlar elektron juftlarini baham ko'radi.", d: "medium" },
    { q: "Quyidagi moddalardan qaysi biri elektrolit?",
      a: 0, o: ["NaCl eritmasi","Spirt","Distillangan suv","Shakar eritmasi"],
      e: "Elektrolitlar eritmada ionlarga ajraladi va tok o'tkazadi.", d: "medium" },
    { q: "Alyuminiyning valentligi?",
      a: 2, o: ["I","II","III","IV"],
      e: "Alyuminiy (Al) III valentli.", d: "easy" },
  ],
  tarix: [
    { q: "Buyuk Ipak yo'li qaysi qit'alar o'rtasida?",
      a: 1, o: ["Afrika-Amerika","Osiyo-Yevropa","Osiyo-Afrika","Amerika-Yevropa"],
      e: "Ipak yo'li Osiyo va Yevropani bog'lagan.", d: "easy" },
    { q: "O'zbekiston mustaqilligi e'lon qilingan yil?",
      a: 0, o: ["1991","1989","1993","1985"],
      e: "1991 yil 31 avgust — mustaqillik.", d: "easy" },
    { q: "Mona Liza rasmini kim chizgan?",
      a: 2, o: ["Mikelanjelo","Rafael","Leonardo da Vinchi","Van Gog"],
      e: "Mona Liza (La Gioconda) Leonardo da Vinchi asari (~1503).", d: "easy" },
    { q: "Birinchi yozuv qaysi xalq tomonidan ixtiro qilingan?",
      a: 1, o: ["Misrliklar","Shumerlar","Xitoyliklar","Yunonlar"],
      e: "Shumerlar mixxat yozuvini miloddan avval 3200 yil atrofida ixtiro qilgan.", d: "medium" },
    { q: "Buyuk Aleksandr (Makedonskiy) kim?",
      a: 0, o: ["Yunon sarkardasi","Rim imperatori","Misr fir'avni","Fors shohi"],
      e: "Aleksandr Makedonskiy (mil.avv. 356–323) ulug' yunon sarkardasi.", d: "easy" },
    { q: "X-XIII asrlar O'zbekiston hududida qaysi sulola hukmronlik qilgan?",
      a: 1, o: ["Temuriylar","Qoraxoniylar","Shayboniylar","Mamun"],
      e: "Qoraxoniylar (840–1212) Markaziy Osiyoda hukmronlik qilgan.", d: "medium" },
    { q: "Sovet Ittifoqi tuzilgan yil?",
      a: 2, o: ["1917","1918","1922","1924"],
      e: "SSSR 1922 yil 30 dekabrda tuzilgan.", d: "medium" },
    { q: "Buyuk Britaniyaning eng uzoq hukmronlik qilgan qirolichasi?",
      a: 0, o: ["Viktoriya (63 yil)","Yelizaveta II","Anna","Mary"],
      e: "Qirolicha Viktoriya (1837–1901) 63 yil hukmronlik qilgan.", d: "medium" },
    { q: "Xitoyni birlashtirgan birinchi imperator?",
      a: 1, o: ["Konfutsiy","Sin Shi Huangdi","Sun Yatsen","Mao Zedong"],
      e: "Sin Shi Huangdi (mil.avv. 221) Xitoyni birlashtirgan birinchi imperator.", d: "medium" },
    { q: "Buyuk Fransuz inqilobining asosiy shiori?",
      a: 1, o: ["Tinchlik va taraqqiyot","Erkinlik, tenglik, birodarlik","Barcha ishchilar birlashing","Xalq hokimiyati"],
      e: "Liberté, Égalité, Fraternité — Erkinlik, Tenglik, Birodarlik.", d: "medium" },
    { q: "Birinchi jahon urushida qatnashgan asosiy bloklar?",
      a: 0, o: ["Antanta vs Uchlar ittifoqi","NATO vs Varshava","Ittifoqchilar vs O'q","Sharq vs G'arb"],
      e: "Antanta (Fransiya, Britaniya, Rossiya) vs Uchlar ittifoqi (Germaniya, Avstriya, Italiya).", d: "medium" },
    { q: "Atilla kim edi?",
      a: 2, o: ["Rim imperatori","Yunon faylasufi","Hunlar rahbari","Misr fir'avni"],
      e: "Atilla (406–453) — Hunlar imperiyasining eng kuchli rahbari.", d: "medium" },
    { q: "Yangi dunyoni kim kashf etdi (1492)?",
      a: 0, o: ["Kolumb","Magellan","Vasko da Gama","Amerigo"],
      e: "Kristofor Kolumb 1492 yilda Amerikani kashf etgan (Yangi dunyo).", d: "easy" },
    { q: "O'zbekiston Konstitutsiyasi qachon qabul qilindi?",
      a: 1, o: ["1991 yil","1992 yil 8 dekabr","1993 yil","1995 yil"],
      e: "O'zbekiston Konstitutsiyasi 1992 yil 8 dekabrda qabul qilingan.", d: "easy" },
    { q: "Vatan urushi qaysi yillarda bo'lgan (1941-1945)?",
      a: 0, o: ["1941-1945","1939-1945","1940-1944","1942-1946"],
      e: "Ikkinchi jahon urushi 1939-1945, Vatan urushi 1941-1945.", d: "easy" },
    { q: "Amir Temur davlatining poytaxti?",
      a: 1, o: ["Buxoro","Samarqand","Shahrisabz","Toshkent"],
      e: "Temuriylar poytaxti Samarqand edi.", d: "easy" },
    { q: "Buyuk ipak yo'lining uzunligi?",
      a: 1, o: ["~5000 km","~6400 km","~10000 km","~3000 km"],
      e: "Ipak yo'li taxminan 6400 km, Xitoydan O'rta er dengizigacha.", d: "medium" },
    { q: "Rim imperiyasi qachon qulagan?",
      a: 2, o: ["300 yil","400 yil","476 yil","500 yil"],
      e: "G'arbiy Rim imperiyasi 476 yilda qulagan (oxirgi imperator taxtdan tushgan).", d: "medium" },
    { q: "Millatlar Ligasi qachon tuzilgan?",
      a: 1, o: ["1918 yil","1920 yil","1925 yil","1914 yil"],
      e: "Millatlar Ligasi 1920 yilda I Jaxon urushidan keyin tuzilgan.", d: "hard" },
    { q: "Qadimgi Misr fir'avnlari eng mashhuri?",
      a: 2, o: ["Tutanxamon","Xeops","Ramses II","Nefertiti"],
      e: "Ramses II (mil.avv. 1279-1213) — eng mashhur fir'avn, buyuk quruvchi.", d: "medium" },
  ],
  ingliz: [
    { q: "'Quickly' qaysi so'z turiga kiradi?",
      a: 2, o: ["Noun","Verb","Adverb","Adjective"],
      e: "Quickly — ravish (adverb).", d: "easy" },
    { q: "Past participle of 'write'?",
      a: 1, o: ["wrote","written","writing","writed"],
      e: "write — wrote — written.", d: "medium" },
    { q: "'They ___ playing football now.'",
      a: 1, o: ["is","are","was","were"],
      e: "They are playing — Present Continuous, they ko'plik.", d: "easy" },
    { q: "Superlative form of 'bad'?",
      a: 1, o: ["badder","worst","worse","most bad"],
      e: "bad → worse → worst (noto'g'ri shakl).", d: "medium" },
    { q: "'I have never ___ to London.' (be)",
      a: 0, o: ["been","being","was","were"],
      e: "Present Perfect: have + V3 (been).", d: "easy" },
    { q: "Qaysi so'z to'g'ri yozilgan?",
      a: 2, o: ["recieve","beleive","receive","acheive"],
      e: "Receive to'g'ri (i before e except after c).", d: "medium" },
    { q: "'___ you like some tea?'",
      a: 0, o: ["Would","Do","Are","Have"],
      e: "'Would you like...?' — taklif qilish uchun.", d: "easy" },
    { q: "Indirect speech: 'She said she ___ tired.'",
      a: 1, o: ["is","was","has been","will be"],
      e: "Indirect speechda zamon siljiydi: is → was.", d: "medium" },
    { q: "'A lot of' qanday otlar bilan ishlatiladi?",
      a: 2, o: ["Faqat countable","Faqat uncountable","Ikkala bilan ham","Faqat ko'plik"],
      e: "'A lot of' countable va uncountable otlar bilan ishlatiladi.", d: "medium" },
    { q: "Future Continuous formulasi?",
      a: 1, o: ["will + V1","will be + Ving","will have + V3","be going to + V1"],
      e: "Future Continuous = will be + V-ing (kelasi davomli zamon).", d: "hard" },
    { q: "'I wish I ___ younger.'",
      a: 1, o: ["am","were","was","had been"],
      e: "I wish + were (barcha shaxslar uchun) — istak ifodalash.", d: "hard" },
    { q: "So'roq gap: '___ you finish the report?'",
      a: 0, o: ["Did","Do","Are","Have"],
      e: "Past Simple so'roq gap: Did + V1 (Did you finish...).", d: "easy" },
    { q: "'Look ___ the picture.'",
      a: 2, o: ["on","in","at","to"],
      e: "Look at — 'ga qaramoq' ma'nosida.", d: "easy" },
    { q: "Ingliz tilida nechta asosiy zamon bor?",
      a: 2, o: ["6","8","12","10"],
      e: "12 zamon: 4 present, 4 past, 4 future.", d: "medium" },
    { q: "Collective noun: 'a ___ of flowers'?",
      a: 0, o: ["bouquet","herd","flock","pack"],
      e: "A bouquet of flowers — guldasta.", d: "medium" },
    { q: "'He used to ___ here.'",
      a: 2, o: ["living","lived","live","lives"],
      e: "Used to + V1 (infinitive) — odat tusiga kirgan ish.", d: "medium" },
    { q: "British vs American: 'flat' vs ___?",
      a: 0, o: ["apartment","elevator","truck","gas"],
      e: "British flat = American apartment.", d: "easy" },
    { q: "Phrasal verb: 'give up' ma'nosi?",
      a: 1, o: ["Berib yubormoq","Taslim bo'lmoq / tark etmoq","Tarqatmoq","O'chirmoq"],
      e: "Give up — voz kechish, tashlab qo'yish, taslim bo'lish.", d: "medium" },
    { q: "'Neither...nor...' qanday gap tuzilishi?",
      a: 1, o: ["Har ikki variant","Ikkala variant ham emas","Yoki...yoki","Faqat bittasi"],
      e: "Neither...nor — ikkala variantni inkor qiladi.", d: "hard" },
    { q: "'Since' va 'for' farqi: '___ 3 o'clock'?",
      a: 0, o: ["Since","For","From","At"],
      e: "Since — aniq vaqt nuqtasi bilan (since 3 o'clock).", d: "medium" },
  ],
  geografiya: [
    { q: "O'zbekiston qaysi qit'ada?",
      a: 0, o: ["Osiyo","Yevropa","Afrika","Amerika"],
      e: "O'zbekiston Osiyo qit'asida.", d: "easy" },
    { q: "Eng katta cho'l (issiq)?",
      a: 2, o: ["Gobi","Kalahari","Sahara","Karakum"],
      e: "Sahara — dunyodagi eng katta issiq cho'l.", d: "easy" },
    { q: "Dunyodagi eng katta orol?",
      a: 1, o: ["Madagaskar","Grenlandiya","Borneo","Yangi Gvineya"],
      e: "Grenlandiya ~2.17 mln km² — dunyodagi eng katta orol.", d: "medium" },
    { q: "Eng chuqur okean nuqtasi (Mariana)?",
      a: 0, o: ["~11,034 m","~8,848 m","~6,000 m","~15,000 m"],
      e: "Mariana botiqlari — ~11,034 m (Tinch okean).", d: "medium" },
    { q: "Avstraliya poytaxti?",
      a: 1, o: ["Sidney","Kanberra","Melburn","Brisben"],
      e: "Kanberra — Avstraliya poytaxti.", d: "easy" },
    { q: "Qaysi daryo O'zbekiston hududidan eng uzun?",
      a: 0, o: ["Sirdaryo","Amudaryo","Zarafshon","Chirchiq"],
      e: "Sirdaryo O'zbekiston hududidan uzunroq oqadi.", d: "medium" },
    { q: "Qit'alarning eng kichigi?",
      a: 1, o: ["Yevropa","Avstraliya","Antarktida","Janubiy Amerika"],
      e: "Avstraliya (7.7 mln km²) — eng kichik qit'a.", d: "easy" },
    { q: "Shimoliy Muz okeanida eng katta orol?",
      a: 0, o: ["Grenlandiya","Shpitsbergen","Novaya Zemlya","Islandiya"],
      e: "Grenlandiya Shimoliy Muz okeanidagi eng katta orol.", d: "medium" },
    { q: "Qaysi davlat ikki qit'ada joylashgan?",
      a: 2, o: ["Xitoy","Hindiston","Turkiya","Yaponiya"],
      e: "Turkiya Osiyo va Yevropa qit'alarida joylashgan.", d: "easy" },
    { q: "O'zbekistondagi eng katta ko'l?",
      a: 1, o: ["Orol dengizi","Aydar ko'li","Sudochie","Tuzkon"],
      e: "Aydar ko'li ~3000 km² — O'zbekistondagi eng katta ko'l (Orol quriganidan keyin).", d: "hard" },
    { q: "Dunyodagi eng qadimgi mustaqil davlat?",
      a: 2, o: ["Yunoniston","Xitoy","Eron","Misr"],
      e: "Eron — 2500+ yillik mustaqil davlatchilik tarixi.", d: "medium" },
    { q: "Yer atmosferasining eng quyi qatlami?",
      a: 0, o: ["Troposfera","Stratosfera","Mezosfera","Termosfera"],
      e: "Troposfera — 0-12 km, ob-havo hodisalari shu qatlamda.", d: "medium" },
    { q: "Qaysi daryo dunyodagi eng ko'p suvli?",
      a: 0, o: ["Amazon","Nil","Yanszı","Missisipi"],
      e: "Amazon daryosi suv sarfi bo'yicha eng katta (~209,000 m³/s).", d: "medium" },
    { q: "Qozog'iston poytaxti?",
      a: 0, o: ["Astana (Nur-Sulton)","Olmaota","Shimkent","Qarag'anda"],
      e: "Qozog'iston poytaxti — Astana (Nur-Sulton).", d: "easy" },
    { q: "Qaysi bo'g'oz Osiyo va Shimoliy Amerikani ajratadi?",
      a: 1, o: ["Gibraltar","Bering","Magellan","Dardanell"],
      e: "Bering bo'g'ozi — Osiyo va Shimoliy Amerika orasida, 92 km eni.", d: "medium" },
    { q: "Janubiy Amerikadagi eng katta davlat?",
      a: 1, o: ["Argentina","Braziliya","Peru","Kolumbiya"],
      e: "Braziliya — ~8.5 mln km², Janubiy Amerikaning eng katta davlati.", d: "easy" },
    { q: "Dunyodagi eng quyi nuqta (quruqlikda)?",
      a: 2, o: ["Mariana","O'lik dengiz (-430 m)","Turfan (-154 m)","Qattara (-133 m)"],
      e: "O'lik dengiz yuzasi ~ -430 m (dengiz sathidan eng past).", d: "hard" },
    { q: "O'zbekistonning eng baland tog' cho'qqisi?",
      a: 0, o: ["Hazrat Sulton (4643 m)","Pik Lenin","Pik Korjenevskoy","Xoja Pir"],
      e: "Hazrat Sulton cho'qqisi 4643 m — O'zbekiston eng baland nuqtasi.", d: "medium" },
    { q: "Yevropadagi eng katta davlat?",
      a: 1, o: ["Germaniya","Rossiya (Yevropa qismi)","Fransiya","Ukraina"],
      e: "Rossiyaning Yevropa qismi eng katta, lekin to'liq Yevropa davlati — Ukraina/Fransiya.", d: "medium" },
    { q: "Dengiz sathidan eng baland shahar?",
      a: 1, o: ["Quito","Lhasa (3650 m)","Bogota","La Paz"],
      e: "La Paz (Boliviya) ~ 3640 m — dunyodagi eng baland poytaxt.", d: "hard" },
  ],
};

const MEMORY_PAIRS_2 = {
  fizika: [
    { term: "Nyuton", definition: "F = ma muallifi" },
    { term: "Einstein", definition: "E = mc² muallifi" },
    { term: "Tesla", definition: "Magnit induksiya birligi" },
    { term: "Joul", definition: "Issiqlik miqdori birligi" },
    { term: "Amper", definition: "Tok kuchi birligi" },
    { term: "Volt", definition: "Elektr kuchlanish birligi" },
    { term: "Om", definition: "Elektr qarshilik birligi" },
    { term: "Gerts", definition: "Chastota birligi" },
    { term: "Arximed", definition: "ρgV kuchi" },
    { term: "Galiley", definition: "Erkin tushish tezligi" },
  ],
  matematika: [
    { term: "Pifagor", definition: "a²+b²=c²" },
    { term: "Faktorial", definition: "n! = 1×2×...×n" },
    { term: "Radian", definition: "180°/π ≈ 57.3°" },
    { term: "Vektor", definition: "Yo'nalish va kattalik" },
    { term: "Matritsa", definition: "Sonlar jadvali" },
    { term: "Derivativ", definition: "Hosila — o'zgarish tezligi" },
    { term: "Integral", definition: "Yuzani hisoblash" },
    { term: "Logarifm", definition: "Darajaning teskarisi" },
    { term: "Kompleks son", definition: "i² = -1" },
    { term: "Geometriya", definition: "Shakllar fan" },
  ],
};

const PUZZLE_WORDS_2 = {
  fizika: [
    { word: "FOTON", hint: "Yorug'lik zarrachasi" },
    { word: "IMPULS", hint: "p = mv" },
    { word: "DINAMIKA", hint: "Kuch va harakat haqidagi fan" },
    { word: "OPTIKA", hint: "Yorug'lik haqidagi fan" },
    { word: "AKUSTIKA", hint: "Tovush haqidagi fan" },
    { word: "TERMODINAMIKA", hint: "Issiqlik haqidagi fan" },
    { word: "ELEKTROSTATIKA", hint: "Tinch zaryadlar haqidagi fan" },
    { word: "GIDROSTATIKA", hint: "Suyuqlik muvozanati" },
  ],
  informatika: [
    { word: "ALGORITM", hint: "Muammoni yechish tartibi" },
    { word: "DEBUG", hint: "Xatolarni topish" },
    { word: "BAYT", hint: "8 bitdan iborat xotira birligi" },
    { word: "SERVIS", hint: "Tarmoqdagi xizmat ko'rsatuvchi dastur" },
    { word: "SHIFRLASH", hint: "Ma'lumotni maxfiy kodga o'girish" },
    { word: "BRAUZER", hint: "Veb-sahifalarni ko'rish dasturi" },
    { word: "OPERSISTEM", hint: "Resurslarni boshqaruvchi asosiy dastur" },
    { word: "UZATISH", hint: "Ma'lumotni bir joydan ikkinchiga jo'natish" },
  ],
};

const TEZKOR_QUESTIONS_2 = {
  fizika: [
    { q: "Yorug'lik tezligi (km/s)?", a: "300000" },
    { q: "g (m/s²)?", a: "9.8" },
    { q: "F = ? × a", a: "m" },
    { q: "P = U × ?", a: "i" },
    { q: "1 kVt = ? Vt", a: "1000" },
    { q: "Chastota birligi?", a: "gerts" },
    { q: "Quvvat birligi?", a: "vatt" },
    { q: "Tok kuchi birligi?", a: "amper" },
    { q: "Kuchlanish birligi?", a: "volt" },
    { q: "Qarshilik birligi?", a: "om" },
    { q: "E = mc² da c nima?", a: "yorug'lik tezligi" },
    { q: "Ovoz tezligi (m/s, havoda)", a: "343" },
    { q: "1 soat = ? sekund", a: "3600" },
    { q: "E = m × ? (energiya)", a: "c2" },
    { q: "Kinetik energiya Ek = mv²/?" , a: "2" },
    { q: "I = ? / R (Ohm qonuni)", a: "u" },
    { q: "Yorug'lik tezligi (m/s)", a: "300000000" },
    { q: "Atom yadrosida neytral zarra?", a: "neytron" },
    { q: "Magnit birligi (kashfiyotchi)", a: "tesla" },
    { q: "Kuch birligi (N)", a: "nyuton" },
  ],
  matematika: [
    { q: "π (2 xonali)?", a: "3.14" },
    { q: "7×8?", a: "56" },
    { q: "log₂(8)?", a: "3" },
    { q: "sin 90°?", a: "1" },
    { q: "cos 0°?", a: "1" },
    { q: "tan 45°?", a: "1" },
    { q: "5!?", a: "120" },
    { q: "0!", a: "1" },
    { q: "√169?", a: "13" },
    { q: "12²?", a: "144" },
    { q: "2¹⁰?", a: "1024" },
    { q: "Uchburchak burchaklari yig'indisi?", a: "180" },
    { q: "Doira yuzasi π × ?", a: "r2" },
    { q: "Kubning qirrasi 3 — hajmi?", a: "27" },
    { q: "2/10 = ? (o'nlik)", a: "0.2" },
    { q: "Kvadrat tomoni 5 — perimetri?", a: "20" },
    { q: "Eng kichik tub son?", a: "2" },
    { q: "Eng kichik natural son?", a: "1" },
    { q: "15% = 0.1?", a: "0.15" },
    { q: "To'g'ri burchak necha gradus?", a: "90" },
  ],
  informatika: [
    { q: "1 KB = ? bayt", a: "1024" },
    { q: "CPU nima?", a: "processor" },
    { q: "HTML to'liq nomi?", a: "hyper text markup language" },
    { q: "HTTP 404?", a: "not found" },
    { q: "CSS to'liq nomi?", a: "cascading style sheets" },
    { q: "RAM to'liq nomi?", a: "random access memory" },
    { q: "1 bayt = ? bit", a: "8" },
    { q: "DNS to'liq nomi?", a: "domain name system" },
    { q: "WWW to'liq nomi?", a: "world wide web" },
    { q: "HTTP 200?", a: "ok" },
    { q: "Ikkilik: 1010 = ?", a: "10" },
    { q: "O'nlik: 15 = ? (ikkilik)", a: "1111" },
    { q: "1 MB = ? KB", a: "1024" },
    { q: "SQL to'liq nomi?", a: "structured query language" },
    { q: "API to'liq nomi?", a: "application programming interface" },
    { q: "JSON to'liq nomi?", a: "javascript object notation" },
    { q: "Ikkilik: 1000 = ?", a: "8" },
    { q: "1 GB = ? MB", a: "1024" },
    { q: "OOP to'liq nomi?", a: "object oriented programming" },
    { q: "FTP to'liq nomi?", a: "file transfer protocol" },
  ],
};

const FLASHCARD_CARDS_2 = {
  fizika: [
    { q: "Atom yadrosidagi musbat zarra?", a: "Proton" },
    { q: "Atom yadrosidagi neytral zarra?", a: "Neytron" },
    { q: "Manfiy zaryadli elementar zarra?", a: "Elektron" },
    { q: "E = hf formulasi nima uchun?", a: "Foton energiyasi (Plank)" },
    { q: "To'lqin uzunligi birligi?", a: "Metr (m)" },
    { q: "Atom yadrosini kim kashf etdi?", a: "Ernest Rezerford (1911)" },
  ],
  matematika: [
    { q: "Determinant 2×2 formulasi?", a: "ad - bc" },
    { q: "Aylananing uzunligi formulasi?", a: "L = 2πr" },
    { q: "(a-b)(a+b) nimaga teng?", a: "a² - b²" },
    { q: "sin(0°) = ?", a: "0" },
    { q: "cos(180°) = ?", a: "-1" },
    { q: "Asosi 3, balandligi 4 bo'lgan uchburchak yuzi?", a: "6" },
  ],
  informatika: [
    { q: "TCP/IP necha qatlamli?", a: "4 qatlam" },
    { q: "Git'da branch birlashtirish?", a: "git merge" },
    { q: "MySQL qanday DB?", a: "Relyatsion (SQL) ma'lumotlar bazasi" },
    { q: "Kompilyator nima qiladi?", a: "Kodni mashina tiliga o'giradi" },
    { q: "Brauzer nima?", a: "Veb-sahifalarni ko'rsatuvchi dastur" },
    { q: "Xato topish jarayoni?", a: "Debugging" },
  ],
  biologiya: [
    { q: "Mitoxondriya vazifasi?", a: "Hujara energiyasi markazi (ATP ishlab chiqaradi)" },
    { q: "Xloroplast vazifasi?", a: "Fotosintez organoidi — yashil rang" },
    { q: "Gemoglobin vazifasi?", a: "Kislorodni tashish" },
    { q: "Odam tanasining eng katta organi?", a: "Teri" },
    { q: "Nafas olish markazi qayerda?", a: "Uzunchoq miya" },
    { q: "Gomeostaz nima?", a: "Ichki muhit barqarorligi" },
  ],
  kimyo: [
    { q: "NaCl nima?", a: "Osh tuzi — natriy xlorid" },
    { q: "pH = 7 nimani bildiradi?", a: "Neytral eritma" },
    { q: "H₂SO₄ nima?", a: "Sulfat kislota" },
    { q: "NaOH nima?", a: "Natriy gidroksid (ishqor)" },
    { q: "C₆H₁₂O₆ nima?", a: "Glyukoza (uzum qandi)" },
    { q: "Katalizator vazifasi?", a: "Reaksiyani tezlashtirish" },
  ],
  tarix: [
    { q: "1991-yil 31-avgust", a: "O'zbekiston mustaqilligi e'lon qilindi" },
    { q: "Temur kim?", a: "XIV asr buyuk sarkarda va davlat arbobi" },
    { q: "Ibn Sino kim?", a: "XI asr tabib va faylasuf" },
    { q: "Al-Xorazmiy kim?", a: "Algebra asoschisi, IX asr matematigi" },
    { q: "Ulug'bek kim?", a: "Astronom, Temur nabirasi (1394-1449)" },
    { q: "Konstitutsiya qachon qabul qilindi?", a: "1992 yil 8 dekabr" },
  ],
  ingliz: [
    { q: "'Beautiful' so'z turkumi?", a: "Adjective (sifat)" },
    { q: "'Quickly' so'z turkumi?", a: "Adverb (ravish)" },
    { q: "'They' qaysi shaxs?", a: "Uchinchi shaxs ko'plik" },
    { q: "'Much' qanday ot bilan?", a: "Uncountable nouns bilan" },
    { q: "'Many' qanday ot bilan?", a: "Countable nouns bilan" },
    { q: "'Has' qaysi shaxslar bilan?", a: "He, she, it (3-shaxs birlik)" },
  ],
  geografiya: [
    { q: "Dunyodagi eng baland sharshara?", a: "Anxel (979 m, Venesuela)" },
    { q: "Dunyodagi eng katta ko'l (maydon)?", a: "Kaspiy dengizi" },
    { q: "Kizil qum cho'li qayerda?", a: "O'zbekiston / Markaziy Osiyo" },
    { q: "Eng kichik davlat?", a: "Vatikan (0.44 km²)" },
    { q: "O'zbekiston eng baland nuqtasi?", a: "Hazrat Sulton (4643 m)" },
    { q: "Chorak qit'alar?", a: "Afro-Evroosiya, Amerika, Antarktida, Avstraliya" },
  ],
};

const TRUE_FALSE_2 = {
  fizika: [
    { s: "Yorug'lik vakuumda ham tarqaladi", a: true, e: "Ha — vakuumda c ≈ 300,000 km/s tezlikda." },
    { s: "Ohm qonuniga ko'ra I = U × R", a: false, e: "I = U/R — tok kuchi kuchlanish va qarshilik nisbati." },
    { s: "Gravitatsiya tezlanishi Yerdada 9.8 m/s² ga yaqin", a: true, e: "g ≈ 9.8 m/s² — standart qiymat." },
    { s: "Issiqlik har doim issiq joydan sovuq joyga o'tadi", a: true, e: "Ikkinchi termodinamika qonuni." },
    { s: "Elektr toki o'tkazgichda elektronlar harakatidan hosil bo'ladi", a: true, e: "Tok — zaryadlangan zarralarning yo'naltirilgan harakati." },
    { s: "Yerning magnit maydoni yo'q", a: false, e: "Yer magnit maydonga ega (geodinamo effekti)." },
    { s: "Ovoz vakuumda tarqaladi", a: false, e: "Ovoz muhit zarralari orqali tarqaladi, vakuumda tarqalmaydi." },
    { s: "Atom yadrosi proton va neytronlardan tashkil topgan", a: true, e: "Yadroda proton (musbat) va neytron (neytral) bor." },
    { s: "Energiya yo'qolishi mumkin", a: false, e: "Energiya saqlanadi, faqat bir turdan ikkinchisiga o'tadi." },
    { s: "Kondensator o'zgarmas tokni o'tkazadi", a: false, e: "Kondensator o'zgarmas tokni o'tkazmaydi (zaryadlanadi)." },
  ],
  matematika: [
    { s: "Har qanday juft son 2 ga bo'linadi", a: true, e: "Juft son — 2 ning karralisi." },
    { s: "π = 3.14 aniq qiymat", a: false, e: "π — cheksiz o'nlik kasr (≈ 3.14159...)." },
    { s: "Manfiy sonning kvadrati musbat", a: true, e: "(-a)² = a² ≥ 0." },
    { s: "Kvadrat tenglama doim 2 ta yechimga ega", a: false, e: "D ga qarab 0, 1 yoki 2 ta ildiz bo'lishi mumkin." },
    { s: "log₂(16) = 4", a: true, e: "2⁴ = 16, shuning uchun log₂(16) = 4." },
    { s: "Uchburchak ichki burchaklari yig'indisi 180°", a: true, e: "Har qanday uchburchakda 180°." },
    { s: "0 soni haqiqiy son emas", a: false, e: "0 haqiqiy son (butun son, neytral element)." },
    { s: "6! = 720", a: true, e: "6! = 1×2×3×4×5×6 = 720." },
    { s: "2⁰ = 0", a: false, e: "2⁰ = 1 — har qanday sonning 0-darajasi 1." },
    { s: "Kubning 12 ta qirrasi bor", a: true, e: "Kubda 6 yoq, 12 qirra, 8 uchi bor." },
  ],
  informatika: [
    { s: "RAM — doimiy xotira", a: false, e: "RAM vaqtinchalik; doimiy — ROM/SSD." },
    { s: "1 bayt = 8 bit", a: true, e: "Standart birlik." },
    { s: "HTML — dasturlash tili", a: false, e: "HTML — belgilash (markup) tili." },
    { s: "Python dinamik tipli til", a: true, e: "O'zgaruvchi turi avtomatik aniqlanadi." },
    { s: "HTTP 403 — ruxsat berilmagan", a: true, e: "403 Forbidden — sahifaga kirish taqiqlangan." },
    { s: "CSS Flexbox bir o'lchovli joylashtirish", a: true, e: "Flexbox bir o'lchovli (qator/ustun), Grid ikki o'lchovli." },
    { s: "SQL'da DELETE jadvalni o'chiradi", a: false, e: "DELETE — qatorlarni o'chiradi; DROP TABLE — jadvalni o'chiradi." },
    { s: "Java va JavaScript bir xil", a: false, e: "Umuman farqli tillar, faqat nomi o'xshash." },
    { s: "Git — versiya nazorat tizimi", a: true, e: "Git o'zgarishlarni kuzatish va hamkorlikda ishlash uchun." },
    { s: "Algoritm chekli qadamlardan iborat bo'lishi kerak", a: true, e: "Algoritm chekli vaqtdan so'ng tugashi kerak." },
  ],
  biologiya: [
    { s: "Fotosintezda O₂ chiqadi", a: true, e: "Suv molekulasidan kislorod ajraladi." },
    { s: "Odamda 206 ta suyak bor (o'rtacha)", a: true, e: "Voyaga yetgan odamda ~206 ta suyak." },
    { s: "Viruslar tirik organizmlar", a: false, e: "Viruslar hujayradan tashqarida tirik emas, faqat hujayra ichida ko'payadi." },
    { s: "Odam yurakda 4 ta kamera bor", a: true, e: "2 bo'lmacha + 2 qorincha." },
    { s: "Mitoxondriya faqat o'simliklarda bor", a: false, e: "Barcha eukaryot hujayralarda mitoxondriya bor." },
    { s: "DNK ikki spiral shaklida", a: true, e: "Watson-Krik modeli — qo'sh spiral." },
    { s: "Asal asalarilar raqs orqali muloqot qiladi", a: true, e: "Asalarilar 'sakkiz raqsi' bilan oziqa joyini bildiradi." },
    { s: "Odamda 46 ta xromosoma bor", a: true, e: "23 juft xromosoma." },
    { s: "O'simliklar ham nafas oladi", a: true, e: "O'simliklar fotosintez bilan birga nafas oladi." },
    { s: "Barcha bakteriyalar zararli", a: false, e: "Ko'pchilik bakteriyalar foydali yoki zararsiz." },
  ],
  kimyo: [
    { s: "Suvning qaynash harorati 100°C (1 atm)", a: true, e: "Standart atmosfera bosimida." },
    { s: "NaCl — kislota", a: false, e: "NaCl — tuz (neytral tuz)." },
    { s: "H₂O₂ — vodorod peroksid", a: true, e: "Vodorod peroksid dezinfektsiya uchun ishlatiladi." },
    { s: "Kislorod atom raqami 16", a: false, e: "Kislorod atom raqami 8 (O)." },
    { s: "Metan CH₄ — organik modda", a: true, e: "Metan eng oddiy organik birikma (alkan)." },
    { s: "Davriy jadvalda 118 ta element bor", a: true, e: "Hozirgi kunda 118 ta element ma'lum." },
    { s: "Neytrallanishda tuz va suv hosil bo'ladi", a: true, e: "Kislota + Ishqor → Tuz + Suv." },
    { s: "Og'ir suv D₂O dan iborat", a: true, e: "Og'ir suvda vodorod o'rniga deyteriy (²H)." },
    { s: "Tabiiy gaz hidsiz", a: true, e: "Gaz hidsiz, lekin sizib chiqishini bilish uchun hid qo'shiladi." },
    { s: "Pt (platina) — eng og'ir metall", a: false, e: "Osmiy (Os) eng og'ir metall (22.59 g/cm³)." },
  ],
  tarix: [
    { s: "O'zbekiston 1991-yilda mustaqillik oldi", a: true, e: "31 avgust 1991 — mustaqillik." },
    { s: "Buyuk Ipak yo'li faqat Yevropada o'tgan", a: false, e: "Osiyo va Yevropani bog'lagan." },
    { s: "Amir Temur 1405 yilda vafot etgan", a: true, e: "1405 yil fevral, Otror shahrida." },
    { s: "Ibn Sino tibbiyot olimi", a: true, e: "'Tib qonunlari' XI asrda yozilgan." },
    { s: "Ikkinchi jahon urushi 1941 yilda boshlangan", a: false, e: "1939 yil 1 sentabrda boshlangan (Polsha bostirilishi)." },
    { s: "Xitoy devori kosmosdan ko'rinadi", a: false, e: "Bu afsona — Xitoy devori kosmosdan ko'rinmaydi." },
    { s: "Gutenberg bosmaxonani ixtiro qilgan", a: true, e: "~1440 yil, kitob nashr etishni o'zgartirgan." },
    { s: "Kolumb Hindistonga suzib ketayotib Amerikani kashf etgan", a: true, e: "1492 yil, u Hindistonga yetdim deb o'ylagan." },
    { s: "Birinchi Olimpiada o'yinlari Rimda bo'lgan", a: false, e: "Miloddan avval 776, Gretsiyaning Olimpiya shahrida." },
    { s: "Buyuk Britaniya YeI dan chiqqan (Brexit)", a: true, e: "2020 yil 31 yanvar — Brexit amalga oshgan." },
  ],
  ingliz: [
    { s: "'Quickly' — ravish (adverb)", a: true, e: "Quick (sifat) + -ly = quickly." },
    { s: "Past simple of 'go' is 'goed'", a: false, e: "go — went — gone." },
    { s: "'I am' qisqartmasi 'I'm'", a: true, e: "I am = I'm." },
    { s: "'Children' ko'plik shakli", a: true, e: "Child → Children (noto'g'ri ko'plik)." },
    { s: "'She don't like coffee' to'g'ri", a: false, e: "She doesn't like coffee (3-shaxs birlik)." },
    { s: "'He has been working' — Present Perfect Continuous", a: true, e: "have/has + been + Ving." },
    { s: "Ingliz tilida 26 ta harf bor", a: true, e: "A-Z gacha 26 harf." },
    { s: "'Good' — comparative 'gooder'", a: false, e: "good → better → best." },
    { s: "'There is' birlik, 'there are' ko'plik uchun", a: true, e: "There is a book. There are books." },
    { s: "'Can' o'tgan zamoni 'could'", a: true, e: "can → could (I can swim → I could swim)." },
  ],
  geografiya: [
    { s: "O'zbekiston Osiyo qit'asida", a: true, e: "Markaziy Osiyo — Osiyo qit'asi." },
    { s: "Sahara — eng katta cho'l", a: true, e: "Issiq cho'llar ichida eng katta." },
    { s: "Amazon daryosi Afrikada", a: false, e: "Amazon Janubiy Amerikada." },
    { s: "Avstraliya qit'a va davlat", a: true, e: "Yagona davlat butun qit'ani egallagan." },
    { s: "Yer Quyosh atrofida 24 soatda aylanadi", a: false, e: "365.25 kun (1 yil). 24 soat — o'z o'qi atrofida." },
    { s: "O'zbekiston ikki dengizga chiqishga ega", a: false, e: "O'zbekiston dengizga chiqish yo'q (quruqlik bilan o'ralgan)." },
    { s: "Orol dengizi qurib bormoqda", a: true, e: "1960-yillardan boshlab suv sathi keskin kamaygan." },
    { s: "Yaponiyada 4000 dan ortiq orol bor", a: true, e: "Yaponiya 6852 oroldan iborat." },
    { s: "Nil daryosi Hindistonda", a: false, e: "Nil daryosi Afrikada (Misr, Sudan)." },
    { s: "Kaspiy dengizi — dunyodagi eng katta ko'l", a: true, e: "371,000 km², 'dengiz' deb ataladi, lekin ko'l." },
  ],
};

const ORDER_QUESTIONS_2 = {
  tarix: [
    { prompt: "Quyidagi voqealarni xronologik tartibda joylashtiring (eski → yangi):",
      items: ["Temuriylar davri", "O'zbekiston mustaqilligi", "Amir Temur saltanati", "Konstitutsiya qabul qilindi (1992)"],
      order: [0, 2, 1, 3] },
    { prompt: "Tarixiy davrlarni eskidan yangiga tartiblang:",
      items: ["Neolit davri", "O'rta asrlar", "Temuriylar", "Zamonaviy davr"],
      order: [0, 1, 2, 3] },
    { prompt: "Hukmdorlarni xronologik tartibda joylashtiring:",
      items: ["Amir Temur", "Ulug'bek", "Bobur", "Shayboniyxon"],
      order: [0, 1, 3, 2] },
    { prompt: "Voqealarni eskidan yangiga tartiblang:",
      items: ["Fransuz inqilobi", "Ikkinchi jahon urushi", "Buyuk Ipak yo'li", "Kosmosga ilk parvoz"],
      order: [2, 0, 1, 3] },
  ],
  fizika: [
    { prompt: "Fizik kattaliklarni o'lchov birliklari bilan moslang (kichik → katta):",
      items: ["Millimetr", "Metr", "Kilometr", "Santimetr"],
      order: [0, 3, 1, 2] },
    { prompt: "Yorug'lik spektrini to'lqin uzunligi bo'yicha (qisqa → uzun):",
      items: ["Ko'k", "Qizil", "Yashil", "Binafsha"],
      order: [3, 0, 2, 1] },
    { prompt: "Energiya turlarini (miqdori bo'yicha kam → ko'p):",
      items: ["Foton", "Elektron", "Atom yadrosi", "Geliy atomi"],
      order: [0, 1, 3, 2] },
  ],
  matematika: [
    { prompt: "Sonlarni o'sish tartibida joylashtiring:",
      items: ["-3", "0", "2", "5"],
      order: [0, 1, 2, 3] },
    { prompt: "Amallarni to'g'ri bajarish tartibi:",
      items: ["Qavs", "Ko'paytirish", "Qo'shish", "Daraja"],
      order: [0, 3, 1, 2] },
    { prompt: "Sonlarni o'sish tartibida:",
      items: ["0.5", "1/4", "0.75", "3/4"],
      order: [1, 0, 2, 3] },
    { prompt: "Geometrik shakllarni tomonlari soni bo'yicha (kam → ko'p):",
      items: ["To'rtburchak", "Uchburchak", "Oltiburchak", "Beshburchak"],
      order: [1, 0, 3, 2] },
  ],
  informatika: [
    { prompt: "Xotira birliklarini kichikdan kattaga tartiblang:",
      items: ["Bit", "Kilobayt", "Bayt", "Megabayt"],
      order: [0, 2, 1, 3] },
    { prompt: "Ma'lumotlar tuzilmalarini murakkablik bo'yicha (sodda → murakkab):",
      items: ["Massiv", "Bog'lamli ro'yxat", "Daraxt", "Graf"],
      order: [0, 1, 2, 3] },
    { prompt: "Dasturlash bosqichlarini to'g'ri tartibda:",
      items: ["Kod yozish", "Test qilish", "Talim tahlili", "Deploy qilish"],
      order: [2, 0, 1, 3] },
  ],
  biologiya: [
    { prompt: "Organizm tuzilishini sodda → murakkab tartiblang:",
      items: ["Hujara", "Organ", "Organizm", "To'qima"],
      order: [0, 3, 1, 2] },
    { prompt: "Hayot turlarini rivojlanish bo'yicha (sodda → murakkab):",
      items: ["Bakteriyalar", "Hasharotlar", "Sutemizuvchilar", "O'simliklar"],
      order: [0, 3, 1, 2] },
    { prompt: "Organlarni joylashuvi bo'yicha (yuqori → past):",
      items: ["Miya", "Jigar", "Oshqozon", "Ichaklar"],
      order: [0, 1, 2, 3] },
  ],
  kimyo: [
    { prompt: "Moddalar holatini (odatda 25°C) tartiblang — qattiq dan suyuq:",
      items: ["Temir", "Suv", "Xlork", "Rux"],
      order: [0, 3, 2, 1] },
    { prompt: "Kislotalilik darajasi bo'yicha (kislotali → ishqoriy):",
      items: ["Limon sharbati", "Toza suv", "Sovun", "Ammiak"],
      order: [0, 1, 2, 3] },
    { prompt: "Atomlarni massasi bo'yicha (yengil → og'ir):",
      items: ["Vodorod H", "Geliy He", "Kislorod O", "Temir Fe"],
      order: [0, 1, 2, 3] },
  ],
  ingliz: [
    { prompt: "Ingliz alifbosini tartiblang:",
      items: ["C", "A", "B", "D"],
      order: [1, 2, 0, 3] },
    { prompt: "So'zlarni ma'no jihatdan (umumiy → xususiy):",
      items: ["Transport", "Mashina toyota", "Mashina", "Mashina toyota camry"],
      order: [0, 2, 1, 3] },
    { prompt: "Zamonlarni (erta → kech):",
      items: ["Present Simple", "Future Simple", "Past Simple", "Present Perfect"],
      order: [2, 0, 3, 1] },
  ],
  geografiya: [
    { prompt: "Geografik ob'ektlarni o'lcham bo'yicha (kichik → katta):",
      items: ["Mamlakat", "Qit'a", "Shahar", "Dunyo"],
      order: [2, 0, 1, 3] },
    { prompt: "Daryolarni uzunligi bo'yicha (qisqa → uzun):",
      items: ["Sirdaryo", "Nil", "Amazon", "Amudaryo"],
      order: [3, 0, 2, 1] },
  ],
};
