name: Deploy Sanity Studio

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install dependencies
        # defaults: run: working-directory o'rniga toza va xavfsiz zanjir usuli
        run: |
          cd studio
          npm install --legacy-peer-deps

      - name: Deploy Sanity Studio
        run: |
          cd studio
          npx sanity deploy --yes
        env:
          SANITY_AUTH_TOKEN: ${{ secrets.SANITY_AUTH_TOKEN }}
